# Generated by Django 4.2.13 on 2024-05-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='departure_address',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='departure_address_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='departure_address_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='destination_address_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='destination_address_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
