# Generated by Django 4.2.13 on 2024-05-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_remove_suppliers_departure_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='final_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='transportational_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
