# Generated by Django 4.2.13 on 2024-05-16 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_regions_center_lat_regions_center_lng'),
        ('suppliers', '0003_suppliers_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='transportational_cost',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='countries.regions'),
        ),
    ]
