# Generated by Django 4.2.13 on 2024-05-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_remove_suppliers_transportational_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliers',
            old_name='final_price',
            new_name='price_exwb',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='price_exws',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
