# Generated by Django 4.2.13 on 2024-05-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_rename_final_price_suppliers_price_exwb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
