# Generated by Django 4.2.13 on 2024-05-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_suppliers_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suppliers',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='specifications',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='comments',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='format',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
