# Generated by Django 4.2.13 on 2024-05-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_supplierprices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierprices',
            name='suppliers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='suppliers.suppliers'),
        ),
        migrations.CreateModel(
            name='SpecificationDocumentSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='specifications/')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='CertificationDocumentSuppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppliers')),
            ],
        ),
    ]
