# Generated by Django 4.2.13 on 2024-06-05 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_default_margin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('countries', '0005_regions_center_lat_regions_center_lng'),
        ('suppliers', '0009_alter_supplierprices_suppliers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationdocumentsuppliers',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='suppliers.suppliers'),
        ),
        migrations.AlterField(
            model_name='specificationdocumentsuppliers',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='suppliers.suppliers'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='countries.regions'),
        ),
    ]
