# Generated by Django 3.2.4 on 2024-06-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_alter_certificationdocumentsuppliers_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
