# Generated by Django 3.2.4 on 2024-05-11 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20240511_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='countries.countries'),
            preserve_default=False,
        ),
    ]
