# Generated by Django 3.2.4 on 2024-05-11 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_regions_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regions',
            old_name='cofficient_price',
            new_name='coefficient_price',
        ),
    ]
