# Generated by Django 4.2.13 on 2024-05-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_rename_cofficient_price_regions_coefficient_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='regions',
            name='center_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='regions',
            name='center_lng',
            field=models.FloatField(default=0),
        ),
    ]
