# Generated by Django 3.2.4 on 2024-05-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mode',
            new_name='team',
        ),
    ]
