# Generated by Django 3.2.4 on 2024-05-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('accounts', '0003_rename_mode_user_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joining_date',
        ),
        migrations.AddField(
            model_name='user',
            name='countries',
            field=models.ManyToManyField(related_name='users', to='countries.Countries'),
        ),
    ]
