france = [
    {'ISO3166-2': 'FR-28', 'admin_level': '6', 'name': 'Eure-et-Loir', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-24', 'admin_level': '6', 'name': 'Dordogne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-40', 'admin_level': '6', 'name': 'Landes', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-86', 'admin_level': '6', 'name': 'Vienne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-51', 'admin_level': '6', 'name': 'Marne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-04', 'admin_level': '6', 'name': 'Alpes-de-Haute-Provence', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-15', 'admin_level': '6', 'name': 'Cantal', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-55', 'admin_level': '6', 'name': 'Meuse', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-77', 'admin_level': '6', 'name': 'Seine-et-Marne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-88', 'admin_level': '6', 'name': 'Vosges', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-06', 'admin_level': '6', 'name': 'Alpes-Maritimes', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-01', 'admin_level': '6', 'name': 'Ain', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-82', 'admin_level': '6', 'name': 'Tarn-et-Garonne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-93', 'admin_level': '6', 'name': 'Seine-Saint-Denis', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-83', 'admin_level': '6', 'name': 'Var', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-89', 'admin_level': '6', 'name': 'Yonne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-13', 'admin_level': '6', 'name': 'Bouches-du-Rhône', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-62', 'admin_level': '6', 'name': 'Pas-de-Calais', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-08', 'admin_level': '6', 'name': 'Ardennes', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-52', 'admin_level': '6', 'name': 'Haute-Marne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-71', 'admin_level': '6', 'name': 'Saône-et-Loire', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-22', 'admin_level': '6', 'name': "Côtes-d'Armor", 'border_type': 'departement'},
    {'ISO3166-2': 'FR-41', 'admin_level': '6', 'name': 'Loir-et-Cher', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-59', 'admin_level': '6', 'name': 'Nord', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-91', 'admin_level': '6', 'name': 'Essonne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-85', 'admin_level': '6', 'name': 'Vendée', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-68', 'admin_level': '6', 'name': 'Haut-Rhin', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-50', 'admin_level': '6', 'name': 'Manche', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-33', 'admin_level': '6', 'name': 'Gironde', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-63', 'admin_level': '6', 'name': 'Puy-de-Dôme', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-74', 'admin_level': '6', 'name': 'Haute-Savoie', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-37', 'admin_level': '6', 'name': 'Indre-et-Loire', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-49', 'admin_level': '6', 'name': 'Maine-et-Loire', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-90', 'admin_level': '6', 'name': 'Territoire-de-Belfort', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-02', 'admin_level': '6', 'name': 'Aisne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-31', 'admin_level': '6', 'name': 'Haute-Garonne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-67', 'admin_level': '6', 'name': 'Bas-Rhin', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-36', 'admin_level': '6', 'name': 'Indre', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-87', 'admin_level': '6', 'name': 'Haute-Vienne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-61', 'admin_level': '6', 'name': 'Orne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-42', 'admin_level': '6', 'name': 'Loire', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-48', 'admin_level': '6', 'name': 'Lozère', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-32', 'admin_level': '6', 'name': 'Gers', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-70', 'admin_level': '6', 'name': 'Haute-Saône', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-21', 'admin_level': '6', 'name': "Côte-d'Or", 'border_type': 'departement'},
    {'ISO3166-2': 'FR-73', 'admin_level': '6', 'name': 'Savoie', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-76', 'admin_level': '6', 'name': 'Seine-Maritime', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-60', 'admin_level': '6', 'name': 'Oise', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-16', 'admin_level': '6', 'name': 'Charente', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-34', 'admin_level': '6', 'name': 'Hérault', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-07', 'admin_level': '6', 'name': 'Ardèche', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-17', 'admin_level': '6', 'name': 'Charente-Maritime', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-44', 'admin_level': '6', 'name': 'Loire-Atlantique', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-95', 'admin_level': '6', 'name': "Val-d'Oise", 'border_type': 'departement'},
    {'ISO3166-2': 'FR-26', 'admin_level': '6', 'name': 'Drôme', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-27', 'admin_level': '6', 'name': 'Eure', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-05', 'admin_level': '6', 'name': 'Hautes-Alpes', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-38', 'admin_level': '6', 'name': 'Isère', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-53', 'admin_level': '6', 'name': 'Mayenne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-09', 'admin_level': '6', 'name': 'Ariège', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-45', 'admin_level': '6', 'name': 'Loiret', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-10', 'admin_level': '6', 'name': 'Aube', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-81', 'admin_level': '6', 'name': 'Tarn', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-72', 'admin_level': '6', 'name': 'Sarthe', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-84', 'admin_level': '6', 'name': 'Vaucluse', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-11', 'admin_level': '6', 'name': 'Aude', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-56', 'admin_level': '6', 'name': 'Morbihan', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-58', 'admin_level': '6', 'name': 'Nièvre', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-92', 'admin_level': '6', 'name': 'Hauts-de-Seine', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-64', 'admin_level': '6', 'name': 'Pyrénées-Atlantiques', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-12', 'admin_level': '6', 'name': 'Aveyron', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-43', 'admin_level': '6', 'name': 'Haute-Loire', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-14', 'admin_level': '6', 'name': 'Calvados', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-46', 'admin_level': '6', 'name': 'Lot', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-79', 'admin_level': '6', 'name': 'Deux-Sèvres', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-18', 'admin_level': '6', 'name': 'Cher', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-78', 'admin_level': '6', 'name': 'Yvelines', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-94', 'admin_level': '6', 'name': 'Val-de-Marne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-23', 'admin_level': '6', 'name': 'Creuse', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-39', 'admin_level': '6', 'name': 'Jura', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-30', 'admin_level': '6', 'name': 'Gard', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-25', 'admin_level': '6', 'name': 'Doubs', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-80', 'admin_level': '6', 'name': 'Somme', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-19', 'admin_level': '6', 'name': 'Corrèze', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-35', 'admin_level': '6', 'name': 'Ille-et-Vilaine', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-66', 'admin_level': '6', 'name': 'Pyrénées-Orientales', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-65', 'admin_level': '6', 'name': 'Hautes-Pyrénées', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-57', 'admin_level': '6', 'name': 'Moselle', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-54', 'admin_level': '6', 'name': 'Meurthe-et-Moselle', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-75C', 'admin_level': '6', 'name': 'Paris'},
    {'ISO3166-2': 'FR-2B', 'admin_level': '6', 'name': 'Haute-Corse', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-2A', 'admin_level': '6', 'name': 'Corse-du-Sud', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-29', 'admin_level': '6', 'name': 'Finistère', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-47', 'admin_level': '6', 'name': 'Lot-et-Garonne', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-03', 'admin_level': '6', 'name': 'Allier', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-69M', 'admin_level': '6', 'name': 'Métropole de Lyon', 'border_type': 'departement'},
    {'ISO3166-2': 'FR-69', 'admin_level': '6', 'name': 'Rhône', 'border_type': 'departement'},
]
albania = [
    {'ISO3166-2': 'AL-10', 'admin_level': '6', 'name:en': 'Shkodër County'},
    {'ISO3166-2': 'AL-08', 'admin_level': '6', 'name:en': 'Lezhë County'},
    {'ISO3166-2': 'AL-09', 'admin_level': '6', 'name:en': 'Dibër County'},
    {'ISO3166-2': 'AL-02', 'admin_level': '6', 'name:en': 'Durrës County'},
    {'ISO3166-2': 'AL-11', 'admin_level': '6', 'name:en': 'Tirana County'},
    {'ISO3166-2': 'AL-03', 'admin_level': '6', 'name:en': 'Elbasan County'},
    {'ISO3166-2': 'AL-04', 'admin_level': '6', 'name:en': 'Fier County'},
    {'ISO3166-2': 'AL-01', 'admin_level': '6', 'name:en': 'Berat County'},
    {'ISO3166-2': 'AL-06', 'admin_level': '6', 'name:en': 'Korçë County'},
    {'ISO3166-2': 'AL-05', 'admin_level': '6', 'name:en': 'Gjirokastër County'},
    {'ISO3166-2': 'AL-12', 'admin_level': '6', 'name:en': 'Vlorë County'},
    {'ISO3166-2': 'AL-07', 'admin_level': '6', 'name:en': 'Kukës County'},
]
armenia = [
    {'ISO3166-2': 'AM-SH', 'admin_level': '4', 'name:en': 'Shirak Province'},
    {'ISO3166-2': 'AM-LO', 'admin_level': '4', 'name:en': 'Lori Province'},
    {'ISO3166-2': 'AM-TV', 'admin_level': '4', 'name:en': 'Tavush Province'},
    {'ISO3166-2': 'AM-AR', 'admin_level': '4', 'name:en': 'Ararat Province'},
    {'ISO3166-2': 'AM-AV', 'admin_level': '4', 'name:en': 'Armavir Province'},
    {'ISO3166-2': 'AM-ER', 'admin_level': '4', 'name:en': 'Yerevan'},
    {'ISO3166-2': 'AM-AG', 'admin_level': '4', 'name:en': 'Aragatsotn Province'},
]
austria = [
    {'ISO3166-2': 'AT-6', 'admin_level': '4', 'name:en': 'Styria'},
    {'ISO3166-2': 'AT-7', 'admin_level': '4', 'name:en': 'Tyrol'},
    {'ISO3166-2': 'AT-2', 'admin_level': '4', 'name:en': 'Carinthia'},
    {'ISO3166-2': 'AT-8', 'admin_level': '4', 'name:en': 'Vorarlberg'},
    {'ISO3166-2': 'AT-1', 'admin_level': '4', 'name:en': 'Burgenland'},
    {'ISO3166-2': 'AT-3', 'admin_level': '4', 'name:en': 'Lower Austria'},
    {'ISO3166-2': 'AT-5', 'admin_level': '4', 'name:en': 'Salzburg'},
    {'ISO3166-2': 'AT-4', 'admin_level': '4', 'name:en': 'Upper Austria'},
    {'ISO3166-2': 'AT-9', 'admin_level': '4', 'name:en': 'Vienna'},
]
azerbaijan = [
    {'ISO3166-2': 'AZ-AGA', 'admin_level': '5', 'name:en': 'Aghstafa District'},
    {'ISO3166-2': 'AZ-BAL', 'admin_level': '5', 'name:en': 'Balakan District'},
    {'ISO3166-2': 'AZ-QAX', 'admin_level': '5', 'name:en': 'Qakh District'},
    {'ISO3166-2': 'AZ-SMX', 'admin_level': '5', 'name:en': 'Samukh District'},
    {'ISO3166-2': 'AZ-TOV', 'admin_level': '5', 'name:en': 'Tovuz District'},
    {'ISO3166-2': 'AZ-ZAQ', 'admin_level': '5', 'name:en': 'Zaqatala District'},
    {'ISO3166-2': 'AZ-SAR', 'admin_level': '5', 'name:en': 'Sharur District'},
    {'ISO3166-2': 'AZ-SAD', 'admin_level': '5', 'name:en': 'Sadarak District'},
    {'ISO3166-2': 'AZ-QAZ', 'admin_level': '5', 'name:en': 'Qazakh District'},
]
bosnia = [
    {'ISO3166-2': 'BA-BRC', 'admin_level': '4', 'name:en': 'Brčko District'},
    {'ISO3166-2': 'BA-BIH', 'admin_level': '4', 'name:en': 'Federation of Bosnia and Herzegovina'},
    {'ISO3166-2': 'BA-SRP', 'admin_level': '4', 'name:en': 'Republika Srpska'},
]
belgium = [
    {'ISO3166-2': 'BE-VAN', 'admin_level': '6', 'name:en': 'Antwerp'},
    {'ISO3166-2': 'BE-VOV', 'admin_level': '6', 'name:en': 'East Flanders'},
    {'ISO3166-2': 'BE-VLI', 'admin_level': '6', 'name:en': 'Limburg'},
    {'ISO3166-2': 'BE-VBR', 'admin_level': '6', 'name:en': 'Flemish Brabant'},
    {'ISO3166-2': 'BE-WBR', 'admin_level': '6', 'name:en': 'Walloon Brabant'},
    {'ISO3166-2': 'BE-WHT', 'admin_level': '6', 'name:en': 'Hainaut'},
    {'ISO3166-2': 'BE-VWV', 'admin_level': '6', 'name:en': 'West Flanders'},
    {'ISO3166-2': 'BE-WNA', 'admin_level': '6', 'name:en': 'Namur'},
    {'ISO3166-2': 'BE-WLG', 'admin_level': '6', 'name:en': 'Liège'},
    {'ISO3166-2': 'BE-WLX', 'admin_level': '6', 'name:en': 'Luxembourg'},
]
bulgaria = [
    {'ISO3166-2': 'BG-24', 'admin_level': '4', 'name:en': 'Stara Zagora'},
    {'ISO3166-2': 'BG-03', 'admin_level': '4', 'name:en': 'Varna'},
    {'ISO3166-2': 'BG-01', 'admin_level': '4', 'name:en': 'Blagoevgrad'},
    {'ISO3166-2': 'BG-02', 'admin_level': '4', 'name:en': 'Burgas'},
    {'ISO3166-2': 'BG-04', 'admin_level': '4', 'name:en': 'Veliko Tarnovo'},
    {'ISO3166-2': 'BG-05', 'admin_level': '4', 'name:en': 'Vidin'},
    {'ISO3166-2': 'BG-06', 'admin_level': '4', 'name:en': 'Vratsa'},
    {'ISO3166-2': 'BG-07', 'admin_level': '4', 'name:en': 'Gabrovo'},
    {'ISO3166-2': 'BG-08', 'admin_level': '4', 'name:en': 'Dobrich'},
    {'ISO3166-2': 'BG-09', 'admin_level': '4', 'name:en': 'Kardzhali'},
    {'ISO3166-2': 'BG-10', 'admin_level': '4', 'name:en': 'Kyustendil'},
    {'ISO3166-2': 'BG-11', 'admin_level': '4', 'name:en': 'Lovech'},
    {'ISO3166-2': 'BG-12', 'admin_level': '4', 'name:en': 'Montana'},
    {'ISO3166-2': 'BG-13', 'admin_level': '4', 'name:en': 'Pazardzhik'},
    {'ISO3166-2': 'BG-14', 'admin_level': '4', 'name:en': 'Pernik'},
    {'ISO3166-2': 'BG-15', 'admin_level': '4', 'name:en': 'Pleven'},
    {'ISO3166-2': 'BG-16', 'admin_level': '4', 'name:en': 'Plovdiv'},
    {'ISO3166-2': 'BG-17', 'admin_level': '4', 'name:en': 'Razgrad'},
    {'ISO3166-2': 'BG-18', 'admin_level': '4', 'name:en': 'Ruse'},
    {'ISO3166-2': 'BG-19', 'admin_level': '4', 'name:en': 'Silistra'},
    {'ISO3166-2': 'BG-20', 'admin_level': '4', 'name:en': 'Sliven'},
    {'ISO3166-2': 'BG-21', 'admin_level': '4', 'name:en': 'Smolyan'},
    {'ISO3166-2': 'BG-23', 'admin_level': '4', 'name:en': 'Sofia'},
    {'ISO3166-2': 'BG-22', 'admin_level': '4', 'name:en': 'Sofia-City'},
    {'ISO3166-2': 'BG-25', 'admin_level': '4', 'name:en': 'Targovishte'},
    {'ISO3166-2': 'BG-26', 'admin_level': '4', 'name:en': 'Haskovo'},
    {'ISO3166-2': 'BG-27', 'admin_level': '4', 'name:en': 'Shumen'},
    {'ISO3166-2': 'BG-28', 'admin_level': '4', 'name:en': 'Yambol'},
]
belarus = [
    {'ISO3166-2': 'BY-HO', 'admin_level': '4', 'name:en': 'Homyel Region'},
    {'ISO3166-2': 'BY-MA', 'admin_level': '4', 'name:en': 'Mahilyow Region'},
    {'ISO3166-2': 'BY-BR', 'admin_level': '4', 'name:en': 'Brest Region'},
    {'ISO3166-2': 'BY-HM', 'admin_level': '4', 'name:en': 'Minsk'},
    {'ISO3166-2': 'BY-HR', 'admin_level': '4', 'name:en': 'Hrodna Region'},
    {'ISO3166-2': 'BY-VI', 'admin_level': '4', 'name:en': 'Vitsebsk Region'},
    {'ISO3166-2': 'BY-MI', 'admin_level': '4', 'name:en': 'Minsk Region'},
]
switzerland = [
    {'ISO3166-2': 'CH-GL', 'admin_level': '4', 'name:en': 'Glarus'},
    {'ISO3166-2': 'CH-LU', 'admin_level': '4', 'name:en': 'Lucerne'},
    {'ISO3166-2': 'CH-BE', 'admin_level': '4', 'name:en': 'Bern'},
    {'ISO3166-2': 'CH-AG', 'admin_level': '4', 'name:en': 'Aargau'},
    {'ISO3166-2': 'CH-BL', 'admin_level': '4', 'name:en': 'Basel-Landschaft'},
    {'ISO3166-2': 'CH-ZG', 'admin_level': '4', 'name:en': 'Zug'},
    {'ISO3166-2': 'CH-OW', 'admin_level': '4', 'name:en': 'Obwalden'},
    {'ISO3166-2': 'CH-NW', 'admin_level': '4', 'name:en': 'Nidwalden'},
    {'ISO3166-2': 'CH-GR', 'admin_level': '4', 'name:en': 'Grisons'},
    {'ISO3166-2': 'CH-AR', 'admin_level': '4', 'name:en': 'Appenzell Ausserrhoden'},
    {'ISO3166-2': 'CH-AI', 'admin_level': '4', 'name:en': 'Appenzell Innerrhoden'},
    {'ISO3166-2': 'CH-VS', 'admin_level': '4', 'name:en': 'Wallis'},
    {'ISO3166-2': 'CH-SG', 'admin_level': '4', 'name:en': 'St. Gallen'},
    {'ISO3166-2': 'CH-TI', 'admin_level': '4', 'name:en': 'Ticino'},
    {'ISO3166-2': 'CH-SZ', 'admin_level': '4', 'name:en': 'Schwyz'},
    {'ISO3166-2': 'CH-ZH', 'admin_level': '4', 'name:en': 'Zurich'},
    {'ISO3166-2': 'CH-TG', 'admin_level': '4', 'name:en': 'Thurgau'},
    {'ISO3166-2': 'CH-UR', 'admin_level': '4', 'name:en': 'Uri'},
    {'ISO3166-2': 'CH-SH', 'admin_level': '4', 'name:en': 'Schaffhausen'},
    {'ISO3166-2': 'CH-JU', 'admin_level': '4', 'name:en': 'Jura'},
    {'ISO3166-2': 'CH-FR', 'admin_level': '4', 'name:en': 'Fribourg'},
    {'ISO3166-2': 'CH-BS', 'admin_level': '4', 'name:en': 'Basel-City'},
    {'ISO3166-2': 'CH-SO', 'admin_level': '4', 'name:en': 'Solothurn'},
    {'ISO3166-2': 'CH-GE', 'admin_level': '4', 'name:en': 'Geneva', 'border_type': 'region'},
    {'ISO3166-2': 'CH-NE', 'admin_level': '4', 'name:en': 'Neuchâtel'},
    {'ISO3166-2': 'CH-VD', 'admin_level': '4', 'name:en': 'Vaud'},

 ]
cyprus = [
    {'ISO3166-2': 'CY-03', 'admin_level': '5', 'name:en': 'Larnaca District'},
    {'ISO3166-2': 'CY-02', 'admin_level': '5', 'name:en': 'Limassol District'},
    {'ISO3166-2': 'CY-05', 'admin_level': '5', 'name:en': 'Paphos District'},
    {'ISO3166-2': 'CY-01', 'admin_level': '5', 'name:en': 'Nicosia District'},
    {'ISO3166-2': 'CY-04', 'admin_level': '5', 'name:en': 'Famagusta District'},
    {'ISO3166-2': 'CY-06', 'admin_level': '5', 'name:en': 'Girne District'},

]
czechia = [
    {'ISO3166-2': 'CZ-10', 'admin_level': '6', 'name:en': 'Capital City of Prague'},
    {'ISO3166-2': 'CZ-64', 'admin_level': '6', 'name:en': 'South Moravian Region'},
    {'ISO3166-2': 'CZ-41', 'admin_level': '6', 'name:en': 'Karlovy Vary Region'},
    {'ISO3166-2': 'CZ-31', 'admin_level': '6', 'name:en': 'South Bohemian Region'},
    {'ISO3166-2': 'CZ-20', 'admin_level': '6', 'name:en': 'Central Bohemian Region'},
    {'ISO3166-2': 'CZ-72', 'admin_level': '6', 'name:en': 'Zlín Region'},
    {'ISO3166-2': 'CZ-42', 'admin_level': '6', 'name:en': 'Ústí nad Labem Region'},
    {'ISO3166-2': 'CZ-63', 'admin_level': '6', 'name:en': 'Vysočina Region'},
    {'ISO3166-2': 'CZ-51', 'admin_level': '6', 'name:en': 'Liberec Region'},
    {'ISO3166-2': 'CZ-71', 'admin_level': '6', 'name:en': 'Olomouc Region'},
    {'ISO3166-2': 'CZ-53', 'admin_level': '6', 'name:en': 'Pardubice Region'},
    {'ISO3166-2': 'CZ-80', 'admin_level': '6', 'name:en': 'Moravian-Silesian Region'},
    {'ISO3166-2': 'CZ-52', 'admin_level': '6', 'name:en': 'Hradec Králové Region'},
    {'ISO3166-2': 'CZ-32', 'admin_level': '6', 'name:en': 'Plzeň Region'},

]
germany = [
    {'ISO3166-2': 'DE-MV', 'admin_level': '4', 'name:en': 'Mecklenburg-Vorpommern'},
    {'ISO3166-2': 'DE-SH', 'admin_level': '4', 'name:en': 'Schleswig-Holstein'},
    {'ISO3166-2': 'DE-RP', 'admin_level': '4', 'name:en': 'Rhineland-Palatinate'},
    {'ISO3166-2': 'DE-TH', 'admin_level': '4', 'name:en': 'Thuringia'},
    {'ISO3166-2': 'DE-SL', 'admin_level': '4', 'name:en': 'Saarland'},
    {'ISO3166-2': 'DE-BE', 'admin_level': '4', 'name:en': 'Berlin'},
    {'ISO3166-2': 'DE-SN', 'admin_level': '4', 'name:en': 'Saxony'},
    {'ISO3166-2': 'DE-BB', 'admin_level': '4', 'name:en': 'Brandenburg'},
    {'ISO3166-2': 'DE-ST', 'admin_level': '4', 'name:en': 'Saxony-Anhalt'},
    {'ISO3166-2': 'DE-BW', 'admin_level': '4', 'name:en': 'Baden-Württemberg'},
    {'ISO3166-2': 'DE-HE', 'admin_level': '4', 'name:en': 'Hesse'},
    {'ISO3166-2': 'DE-HB', 'admin_level': '4', 'name:en': 'Bremen'},
    {'ISO3166-2': 'DE-NW', 'admin_level': '4', 'name:en': 'North Rhine-Westphalia'},
    {'ISO3166-2': 'DE-NI', 'admin_level': '4', 'name:en': 'Lower Saxony'},
    {'ISO3166-2': 'DE-HH', 'admin_level': '4', 'name:en': 'Hamburg'},
    {'ISO3166-2': 'DE-BY', 'admin_level': '4', 'name:en': 'Bavaria'},

]
denmark = [
    {'ISO3166-2': 'DK-82', 'admin_level': '4', 'name:en': 'Central Denmark Region'},
    {'ISO3166-2': 'DK-81', 'admin_level': '4', 'name:en': 'North Denmark Region'},
    {'ISO3166-2': 'DK-83', 'admin_level': '4', 'name:en': 'Region of Southern Denmark'},
    {'ISO3166-2': 'DK-85', 'admin_level': '4', 'name:en': 'Region Zealand'},
    {'ISO3166-2': 'DK-84', 'admin_level': '4', 'name:en': 'Capital Region of Denmark'},

]
estonia = [
    {'ISO3166-2': 'EE-74', 'admin_level': '6', 'name:en': 'Saare County'},
    {'ISO3166-2': 'EE-68', 'admin_level': '6', 'name:en': 'Pärnu County'},
    {'ISO3166-2': 'EE-39', 'admin_level': '6', 'name:en': 'Hiiu County'},
    {'ISO3166-2': 'EE-56', 'admin_level': '6', 'name:en': 'Lääne County'},
    {'ISO3166-2': 'EE-45', 'admin_level': '6', 'name:en': 'Ida-Viru County'},
    {'ISO3166-2': 'EE-37', 'admin_level': '6', 'name:en': 'Harju County'},
    {'ISO3166-2': 'EE-60', 'admin_level': '6', 'name:en': 'Lääne-Viru County'},
    {'ISO3166-2': 'EE-79', 'admin_level': '6', 'name:en': 'Tartu County'},
    {'ISO3166-2': 'EE-81', 'admin_level': '6', 'name:en': 'Valga County'},
    {'ISO3166-2': 'EE-84', 'admin_level': '6', 'name:en': 'Viljandi County'},
    {'ISO3166-2': 'EE-64', 'admin_level': '6', 'name:en': 'Põlva County'},
    {'ISO3166-2': 'EE-52', 'admin_level': '6', 'name:en': 'Järva County'},
    {'ISO3166-2': 'EE-71', 'admin_level': '6', 'name:en': 'Rapla County'},
    {'ISO3166-2': 'EE-87', 'admin_level': '6', 'name:en': 'Võru County'},
    {'ISO3166-2': 'EE-50', 'admin_level': '6', 'name:en': 'Jõgeva County'},

]
spain = [
    {'ISO3166-2': 'ES-IB', 'admin_level': '4', 'name:en': 'Balearic Islands', 'border_type': 'region'},
    {'ISO3166-2': 'ES-RI', 'admin_level': '4', 'name:en': 'Rioja', 'border_type': 'region'},
    {'ISO3166-2': 'ES-CB', 'admin_level': '4', 'name:en': 'Cantabria', 'border_type': 'region'},
    {'ISO3166-2': 'ES-NC', 'admin_level': '4', 'name:en': 'Navarre', 'border_type': 'region'},
    {'ISO3166-2': 'ES-AS', 'admin_level': '4', 'name:en': 'Asturias', 'border_type': 'region'},
    {'ISO3166-2': 'ES-GA', 'admin_level': '4', 'name:en': 'Galicia', 'border_type': 'region'},
    {'ISO3166-2': 'ES-CL', 'admin_level': '4', 'name:en': 'Castile and León', 'border_type': 'region'},
    {'ISO3166-2': 'ES-PV', 'admin_level': '4', 'name:en': 'Autonomous Community of the Basque Country', 'border_type': 'region'},
    {'ISO3166-2': 'ES-VC', 'admin_level': '4', 'name:en': 'Valencian Community', 'border_type': 'region'},
    {'ISO3166-2': 'ES-AN', 'admin_level': '4', 'name:en': 'Andalusia', 'border_type': 'region'},
    {'ISO3166-2': 'ES-AR', 'admin_level': '4', 'name:en': 'Aragon'},
    {'ISO3166-2': 'ES-MC', 'admin_level': '4', 'name:en': 'Region of Murcia', 'border_type': 'region'},
    {'ISO3166-2': 'ES-EX', 'admin_level': '4', 'name:en': 'Extremadura', 'border_type': 'region'},
    {'ISO3166-2': 'ES-CM', 'admin_level': '4', 'name:en': 'Castile-La Mancha', 'border_type': 'region'},
    {'ISO3166-2': 'ES-CT', 'admin_level': '4', 'name:en': 'Catalonia', 'border_type': 'region'},
    {'ISO3166-2': 'ES-MD', 'admin_level': '4', 'name:en': 'Community of Madrid', 'border_type': 'region'},
    {'ISO3166-2': 'ES-CE', 'admin_level': '4', 'name:en': 'Ceuta', 'border_type': 'region'},
    {'ISO3166-2': 'ES-ML', 'admin_level': '4', 'name:en': 'Melilla', 'border_type': 'region'},

]
finland = [
    {'ISO3166-2': 'FI-18', 'admin_level': '6', 'name:en': 'Uusimaa'},
    {'ISO3166-2': 'FI-19', 'admin_level': '6', 'name:en': 'Southwest Finland'},
    {'ISO3166-2': 'IT-FI', 'admin_level': '6', 'name:en': 'Florence'},
    {'ISO3166-2': 'FI-04', 'admin_level': '6', 'name:en': 'South Savo'},
    {'ISO3166-2': 'FI-15', 'admin_level': '6', 'name:en': 'North Savo'},
    {'ISO3166-2': 'FI-06', 'admin_level': '6', 'name:en': 'Kanta-Häme'},
    {'ISO3166-2': 'FI-08', 'admin_level': '6', 'name:en': 'Central Finland'},
    {'ISO3166-2': 'FI-11', 'admin_level': '6', 'name:en': 'Pirkanmaa'},
    {'ISO3166-2': 'FI-03', 'admin_level': '6', 'name:en': 'South Ostrobothnia'},
    {'ISO3166-2': 'FI-07', 'admin_level': '6', 'name:en': 'Central Ostrobothnia'},
    {'ISO3166-2': 'FI-16', 'admin_level': '6', 'name:en': 'Päijät-Häme'},
    {'ISO3166-2': 'FI-10', 'admin_level': '6', 'name:en': 'Lapland'},
    {'ISO3166-2': 'FI-14', 'admin_level': '6', 'name:en': 'North Ostrobothnia'},
    {'ISO3166-2': 'FI-05', 'admin_level': '6', 'name:en': 'Kainuu'},
    {'ISO3166-2': 'FI-13', 'admin_level': '6', 'name:en': 'North Karelia'},
    {'ISO3166-2': 'FI-12', 'admin_level': '6', 'name:en': 'Ostrobothnia'},
    {'ISO3166-2': 'FI-17', 'admin_level': '6', 'name:en': 'Satakunta'},
    {'ISO3166-2': 'FI-02', 'admin_level': '6', 'name:en': 'South Karelia'},
    {'ISO3166-2': 'FI-09', 'admin_level': '6', 'name:en': 'Kymenlaakso'},
    {'ISO3166-2': 'FI-01', 'admin_level': '6', 'name:en': 'Åland Islands'},

]
united_kingdom = [
    {'ISO3166-2': 'GB-HEF', 'admin_level': '6', 'name': 'Herefordshire'},
    {'ISO3166-2': 'GB-SFK', 'admin_level': '6', 'name': 'Suffolk'},
    {'ISO3166-2': 'GB-LND', 'admin_level': '6', 'name': 'City of London'},
    {'ISO3166-2': 'GB-HRT', 'admin_level': '6', 'name': 'Hertfordshire'},
    {'ISO3166-2': 'GB-NFK', 'admin_level': '6', 'name': 'Norfolk'},
    {'ISO3166-2': 'GB-RUT', 'admin_level': '6', 'name': 'Rutland'},
    {'ISO3166-2': 'GB-WAR', 'admin_level': '6', 'name': 'Warwickshire'},
    {'ISO3166-2': 'GB-WIL', 'admin_level': '6', 'name': 'Wiltshire'},
    {'ISO3166-2': 'GB-CMN', 'admin_level': '6', 'name': 'Sir Gaerfyrddin / Carmarthenshire'},
    {'ISO3166-2': 'GB-PEM', 'admin_level': '6', 'name': 'Pembrokeshire'},
    {'ISO3166-2': 'GB-CON', 'admin_level': '6', 'name': 'Cornwall'},
    {'ISO3166-2': 'GB-BST', 'admin_level': '6', 'name': 'City of Bristol'},
    {'ISO3166-2': 'GB-WOR', 'admin_level': '6', 'name': 'Worcestershire'},
    {'ISO3166-2': 'GB-SRY', 'admin_level': '6', 'name': 'Surrey'},
    {'ISO3166-2': 'GB-KHL', 'admin_level': '6', 'name': 'Kingston upon Hull'},
    {'ISO3166-2': 'GB-NEL', 'admin_level': '6', 'name': 'North East Lincolnshire'},
    {'ISO3166-2': 'GB-SOM', 'admin_level': '6', 'name': 'Somerset'},
    {'ISO3166-2': 'GB-OXF', 'admin_level': '6', 'name': 'Oxfordshire'},
    {'ISO3166-2': 'GB-SOS', 'admin_level': '6', 'name': 'Southend-on-Sea'},
    {'ISO3166-2': 'GB-THR', 'admin_level': '6', 'name': 'Thurrock'},
    {'ISO3166-2': 'GB-CGN', 'admin_level': '6', 'name': 'Ceredigion'},
    {'ISO3166-2': 'GB-LIN', 'admin_level': '6', 'name': 'Lincolnshire'},
    {'ISO3166-2': 'GB-NSM', 'admin_level': '6', 'name': 'North Somerset'},
    {'ISO3166-2': 'GB-BAS', 'admin_level': '6', 'name': 'Bath and North East Somerset'},
    {'ISO3166-2': 'GB-SGC', 'admin_level': '6', 'name': 'South Gloucestershire'},
    {'ISO3166-2': 'GB-GLS', 'admin_level': '6', 'name': 'Gloucestershire'},
    {'ISO3166-2': 'GB-SWA', 'admin_level': '6', 'name': 'Swansea'},
    {'ISO3166-2': 'GB-NBL', 'admin_level': '6', 'name': 'Northumberland'},
    {'ISO3166-2': 'GB-DUR', 'admin_level': '6', 'name': 'County Durham'},
    {'ISO3166-2': 'GB-NYK', 'admin_level': '6', 'name': 'North Yorkshire'},
    {'ISO3166-2': 'GB-LAN', 'admin_level': '6', 'name': 'Lancashire'},
    {'ISO3166-2': 'GB-ERY', 'admin_level': '6', 'name': 'East Riding of Yorkshire'},
    {'ISO3166-2': 'GB-NTL', 'admin_level': '6', 'name': 'Neath Port Talbot'},
    {'ISO3166-2': 'GB-ESX', 'admin_level': '6', 'name': 'East Sussex'},
    {'ISO3166-2': 'GB-BGE', 'admin_level': '6', 'name': 'Bridgend'},
    {'ISO3166-2': 'GB-VGL', 'admin_level': '6', 'name': 'Vale of Glamorgan'},
    {'ISO3166-2': 'GB-NLN', 'admin_level': '6', 'name': 'North Lincolnshire'},
    {'ISO3166-2': 'GB-SWD', 'admin_level': '6', 'name': 'Swindon'},
    {'ISO3166-2': 'GB-WNM', 'admin_level': '6', 'name': 'Windsor and Maidenhead'},
    {'ISO3166-2': 'GB-BRC', 'admin_level': '6', 'name': 'Bracknell Forest'},
    {'ISO3166-2': 'GB-WSX', 'admin_level': '6', 'name': 'West Sussex'},
    {'ISO3166-2': 'GB-BNH', 'admin_level': '6', 'name': 'Brighton and Hove'},
    {'ISO3166-2': 'GB-WOK', 'admin_level': '6', 'name': 'Wokingham'},
    {'ISO3166-2': 'GB-RDG', 'admin_level': '6', 'name': 'Reading'},
    {'ISO3166-2': 'GB-WBK', 'admin_level': '6', 'name': 'West Berkshire'},
    {'ISO3166-2': 'GB-SLG', 'admin_level': '6', 'name': 'Slough'},
    {'ISO3166-2': 'GB-NGM', 'admin_level': '6', 'name': 'City of Nottingham'},
    {'ISO3166-2': 'GB-POR', 'admin_level': '6', 'name': 'Portsmouth'},
    {'ISO3166-2': 'GB-STH', 'admin_level': '6', 'name': 'Southampton'},
    {'ISO3166-2': 'GB-POW', 'admin_level': '6', 'name': 'Powys'},
    {'ISO3166-2': 'GB-YOR', 'admin_level': '6', 'name': 'York'},
    {'ISO3166-2': 'GB-WRX', 'admin_level': '6', 'name': 'Wrexham'},
    {'ISO3166-2': 'GB-DER', 'admin_level': '6', 'name': 'Derby'},
    {'ISO3166-2': 'GB-WRT', 'admin_level': '6', 'name': 'Warrington'},
    {'ISO3166-2': 'GB-HAL', 'admin_level': '6', 'name': 'Halton'},
    {'ISO3166-2': 'GB-BPL', 'admin_level': '6', 'name': 'Blackpool'},
    {'ISO3166-2': 'GB-BBD', 'admin_level': '6', 'name': 'Blackburn with Darwen'},
    {'ISO3166-2': 'GB-MDB', 'admin_level': '6', 'name': 'Middlesbrough'},
    {'ISO3166-2': 'GB-RCC', 'admin_level': '6', 'name': 'Redcar and Cleveland'},
    {'ISO3166-2': 'GB-STT', 'admin_level': '6', 'name': 'Stockton-on-Tees'},
    {'ISO3166-2': 'GB-HPL', 'admin_level': '6', 'name': 'Hartlepool'},
    {'ISO3166-2': 'GB-DAL', 'admin_level': '6', 'name': 'Darlington'},
    {'ISO3166-2': 'GB-CHE', 'admin_level': '6', 'name': 'Cheshire East'},
    {'ISO3166-2': 'GB-CHW', 'admin_level': '6', 'name': 'Cheshire West and Chester'},
    {'ISO3166-2': 'GB-IOW', 'admin_level': '6', 'name': 'Isle of Wight'},
    {'ISO3166-2': 'GB-MDW', 'admin_level': '6', 'name': 'Medway'},
    {'ISO3166-2': 'GB-IOS', 'admin_level': '6', 'name': 'Isles of Scilly'},
    {'ISO3166-2': 'GB-LUT', 'admin_level': '6', 'name': 'Luton'},
    {'ISO3166-2': 'GB-BDF', 'admin_level': '6', 'name': 'Bedford'},
    {'ISO3166-2': 'GB-PTE', 'admin_level': '6', 'name': 'City of Peterborough'},
    {'ISO3166-2': 'GB-CBF', 'admin_level': '6', 'name': 'Central Bedfordshire'},
    {'ISO3166-2': 'GB-TOB', 'admin_level': '6', 'name': 'Torbay'},
    {'ISO3166-2': 'GB-LCE', 'admin_level': '6', 'name': 'City of Leicester'},
    {'ISO3166-2': 'GB-STE', 'admin_level': '6', 'name': 'Stoke-on-Trent'},
    {'ISO3166-2': 'GB-TFW', 'admin_level': '6', 'name': 'Telford and Wrekin'},
    {'ISO3166-2': 'GB-SHR', 'admin_level': '6', 'name': 'Shropshire'},
    {'ISO3166-2': 'GB-KEN', 'admin_level': '6', 'name': 'Kent'},
    {'ISO3166-2': 'GB-MIK', 'admin_level': '6', 'name': 'City of Milton Keynes'},
    {'ISO3166-2': 'GB-HAM', 'admin_level': '6', 'name': 'Hampshire'},
    {'ISO3166-2': 'GB-CAM', 'admin_level': '6', 'name': 'Cambridgeshire'},
    {'ISO3166-2': 'GB-ESS', 'admin_level': '6', 'name': 'Essex'},
    {'ISO3166-2': 'GB-NTT', 'admin_level': '6', 'name': 'Nottinghamshire'},
    {'ISO3166-2': 'GB-LEC', 'admin_level': '6', 'name': 'Leicestershire'},
    {'ISO3166-2': 'GB-PLY', 'admin_level': '6', 'name': 'Plymouth'},
    {'ISO3166-2': 'GB-DEV', 'admin_level': '6', 'name': 'Devon'},
    {'ISO3166-2': 'GB-DEN', 'admin_level': '6', 'name': 'Denbighshire'},
    {'ISO3166-2': 'GB-DBY', 'admin_level': '6', 'name': 'Derbyshire'},
    {'ISO3166-2': 'GB-STS', 'admin_level': '6', 'name': 'Staffordshire'},
    {'ISO3166-2': 'GB-FLN', 'admin_level': '6', 'name': 'Flintshire'},
    {'ISO3166-2': 'GB-GWN', 'admin_level': '6', 'name': 'Gwynedd'},
    {'ISO3166-2': 'GB-CWY', 'admin_level': '6', 'name': 'Conwy'},
    {'ISO3166-2': 'GB-AGY', 'admin_level': '6', 'name': 'Ynys Môn / Isle of Anglesey'},
    {'ISO3166-2': 'GB-NWP', 'admin_level': '6', 'name': 'Newport'},
    {'ISO3166-2': 'GB-MON', 'admin_level': '6', 'name': 'Monmouthshire'},
    {'ISO3166-2': 'GB-ORK', 'admin_level': '6', 'name': 'Orkney Islands'},
    {'ISO3166-2': 'GB-HLD', 'admin_level': '6', 'name': 'Highland'},
    {'ISO3166-2': 'GB-CRF', 'admin_level': '6', 'name': 'Cardiff', 'border_type': 'city'},
    {'ISO3166-2': 'GB-AGB', 'admin_level': '6', 'name': 'Argyll and Bute'},
    {'ISO3166-2': 'GB-MRY', 'admin_level': '6', 'name': 'Moray'},
    {'ISO3166-2': 'GB-DGY', 'admin_level': '6', 'name': 'Dumfries and Galloway'},
    {'ISO3166-2': 'GB-ABE', 'admin_level': '6', 'name': 'Aberdeen City'},
    {'ISO3166-2': 'GB-ABD', 'admin_level': '6', 'name': 'Aberdeenshire'},
    {'ISO3166-2': 'GB-STG', 'admin_level': '6', 'name': 'Stirling'},
    {'ISO3166-2': 'GB-FIF', 'admin_level': '6', 'name': 'Fife'},
    {'ISO3166-2': 'GB-GLG', 'admin_level': '6', 'name': 'Glasgow City'},
    {'ISO3166-2': 'GB-NAY', 'admin_level': '6', 'name': 'North Ayrshire'},
    {'ISO3166-2': 'GB-WLN', 'admin_level': '6', 'name': 'West Lothian'},
    {'ISO3166-2': 'GB-PKN', 'admin_level': '6', 'name': 'Perth and Kinross'},
    {'ISO3166-2': 'GB-SCB', 'admin_level': '6', 'name': 'Scottish Borders'},
    {'ISO3166-2': 'GB-WDU', 'admin_level': '6', 'name': 'West Dunbartonshire'},
    {'ISO3166-2': 'GB-EAY', 'admin_level': '6', 'name': 'East Ayrshire'},
    {'ISO3166-2': 'GB-SAY', 'admin_level': '6', 'name': 'South Ayrshire'},
    {'ISO3166-2': 'GB-NLK', 'admin_level': '6', 'name': 'North Lanarkshire'},
    {'ISO3166-2': 'GB-EDU', 'admin_level': '6', 'name': 'East Dunbartonshire'},
    {'ISO3166-2': 'GB-CLK', 'admin_level': '6', 'name': 'Clackmannanshire'},
    {'ISO3166-2': 'GB-FAL', 'admin_level': '6', 'name': 'Falkirk'},
    {'ISO3166-2': 'GB-EDH', 'admin_level': '6', 'name': 'City of Edinburgh'},
    {'ISO3166-2': 'GB-ELN', 'admin_level': '6', 'name': 'East Lothian'},
    {'ISO3166-2': 'GB-MLN', 'admin_level': '6', 'name': 'Midlothian'},
    {'ISO3166-2': 'GB-ANS', 'admin_level': '6', 'name': 'Angus'},
    {'ISO3166-2': 'GB-DND', 'admin_level': '6', 'name': 'Dundee City'},
    {'ISO3166-2': 'GB-ERW', 'admin_level': '6', 'name': 'East Renfrewshire'},
    {'ISO3166-2': 'GB-IVC', 'admin_level': '6', 'name': 'Inverclyde'},
    {'ISO3166-2': 'GB-RFW', 'admin_level': '6', 'name': 'Renfrewshire'},
    {'ISO3166-2': 'GB-SLK', 'admin_level': '6', 'name': 'South Lanarkshire'},
    {'ISO3166-2': 'GB-ELS', 'admin_level': '6', 'name': 'Na h-Eileanan Siar'},
    {'ISO3166-2': 'GB-ZET', 'admin_level': '6', 'name': 'Shetland Islands'},
    {'ISO3166-2': 'GB-TOF', 'admin_level': '6', 'name': 'Torfaen'},
    {'ISO3166-2': 'GB-BGW', 'admin_level': '6', 'name': 'Blaenau Gwent'},
    {'ISO3166-2': 'GB-CAY', 'admin_level': '6', 'name': 'Caerphilly'},
    {'ISO3166-2': 'GB-MTY', 'admin_level': '6', 'name': 'Merthyr Tydfil'},
    {'ISO3166-2': 'GB-RCT', 'admin_level': '6', 'name': 'Rhondda Cynon Taf'},
    {'ISO3166-2': 'GB-BCP', 'admin_level': '6', 'name': 'Bournemouth, Christchurch and Poole'},
    {'ISO3166-2': 'GB-DOR', 'admin_level': '6', 'name': 'Dorset'},
    {'ISO3166-2': 'GB-WNH', 'admin_level': '6', 'name': 'West Northamptonshire'},
    {'ISO3166-2': 'GB-NNH', 'admin_level': '6', 'name': 'North Northamptonshire'},
    {'ISO3166-2': 'GB-BKM', 'admin_level': '6', 'name': 'Buckinghamshire'},

]
georgia = [
    {'ISO3166-2': 'GE-AJ', 'admin_level': '4', 'name:en': 'Autonomous Republic of Adjara'},
    {'ISO3166-2': 'GE-GU', 'admin_level': '4', 'name:en': 'Guria'},
    {'ISO3166-2': 'GE-SJ', 'admin_level': '4', 'name:en': 'Samtskhe-Javakheti'},
    {'ISO3166-2': 'GE-SZ', 'admin_level': '4', 'name:en': 'Samegrelo-Upper Svaneti'},
    {'ISO3166-2': 'GE-TB', 'admin_level': '4', 'name:en': 'Tbilisi'},
    {'ISO3166-2': 'GE-RL', 'admin_level': '4', 'name:en': 'Racha-Lechkhumi and Kvemo Svaneti'},
    {'ISO3166-2': 'GE-IM', 'admin_level': '4', 'name:en': 'Imereti'},
    {'ISO3166-2': 'GE-SK', 'admin_level': '4', 'name:en': 'Shida Kartli'},
    {'ISO3166-2': 'GE-MM', 'admin_level': '4', 'name:en': 'Mtskheta-Mtianeti'},
    {'ISO3166-2': 'GE-KA', 'admin_level': '4', 'name:en': 'Kakheti'},
    {'ISO3166-2': 'GE-KK', 'admin_level': '4', 'name:en': 'Lower Kartli'},
    {'ISO3166-2': 'GE-AB', 'admin_level': '4', 'name:en': 'Autonomous Republic of Abkhazia'},
]
greece = [
    {'ISO3166-2': 'GR-M', 'admin_level': '5', 'name:en': 'Region of Crete'},
    {'ISO3166-2': 'GR-D', 'admin_level': '5', 'name:en': 'Epirus'},
    {'ISO3166-2': 'GR-H', 'admin_level': '5', 'name:en': 'Central Greece'},
    {'ISO3166-2': 'GR-G', 'admin_level': '5', 'name:en': 'Western Greece'},
    {'ISO3166-2': 'GR-A', 'admin_level': '5', 'name:en': 'Eastern Macedonia and Thrace'},
    {'ISO3166-2': 'GR-B', 'admin_level': '5', 'name:en': 'Central Macedonia'},
    {'ISO3166-2': 'GR-C', 'admin_level': '5', 'name:en': 'Western Macedonia'},
    {'ISO3166-2': 'GR-I', 'admin_level': '5', 'name:en': 'Attica'},
    {'ISO3166-2': 'GR-J', 'admin_level': '5', 'name:en': 'Peloponnese Region'},
    {'ISO3166-2': 'GR-F', 'admin_level': '5', 'name:en': 'Ioanian Islands'},
    {'ISO3166-2': 'GR-E', 'admin_level': '5', 'name:en': 'Thessaly'},
    {'ISO3166-2': 'GR-K', 'admin_level': '5', 'name:en': 'Northern Aegean'},
    {'ISO3166-2': 'GR-L', 'admin_level': '5', 'name:en': 'South Aegean'},
]
croatia = [
    {'ISO3166-2': 'HR-14', 'admin_level': '6', 'name:en': 'Osijek-Baranja County'},
    {'ISO3166-2': 'HR-16', 'admin_level': '6', 'name:en': 'Vukovar-Srijem County'},
    {'ISO3166-2': 'HR-12', 'admin_level': '6', 'name:en': 'Brod-Posavina County'},
    {'ISO3166-2': 'HR-10', 'admin_level': '6', 'name:en': 'Virovitica-Podravina County'},
    {'ISO3166-2': 'HR-11', 'admin_level': '6', 'name:en': 'Požega-Slavonia County'},
    {'ISO3166-2': 'HR-03', 'admin_level': '6', 'name:en': 'Sisak-Moslavina County'},
    {'ISO3166-2': 'HR-07', 'admin_level': '6', 'name:en': 'Bjelovar-Bilogora County'},
    {'ISO3166-2': 'HR-20', 'admin_level': '6', 'name:en': 'Međimurje County'},
    {'ISO3166-2': 'HR-06', 'admin_level': '6', 'name:en': 'Koprivnica-Križevci County'},
    {'ISO3166-2': 'HR-05', 'admin_level': '6', 'name:en': 'Varaždin County'},
    {'ISO3166-2': 'HR-02', 'admin_level': '6', 'name:en': 'Krapina-Zagorje County'},
    {'ISO3166-2': 'HR-21', 'admin_level': '6', 'name:en': 'City of Zagreb'},
    {'ISO3166-2': 'HR-01', 'admin_level': '6', 'name:en': 'Zagreb County'},
    {'ISO3166-2': 'HR-04', 'admin_level': '6', 'name:en': 'Karlovac County'},
    {'ISO3166-2': 'HR-18', 'admin_level': '6', 'name:en': 'Istria County'},
    {'ISO3166-2': 'HR-08', 'admin_level': '6', 'name:en': 'Primorje-Gorski Kotar County'},
    {'ISO3166-2': 'HR-09', 'admin_level': '6', 'name:en': 'Lika-Senj County'},
    {'ISO3166-2': 'HR-13', 'admin_level': '6', 'name:en': 'Zadar County'},
    {'ISO3166-2': 'HR-15', 'admin_level': '6', 'name:en': 'Šibenik-Knin County'},
    {'ISO3166-2': 'HR-17', 'admin_level': '6', 'name:en': 'Split-Dalmatia County'},
    {'ISO3166-2': 'HR-19', 'admin_level': '6', 'name:en': 'Dubrovnik-Neretva County'},
]
hungary = [
    {'ISO3166-2': 'HU-SO', 'admin_level': '6', 'name:en': 'Somogy'},
    {'ISO3166-2': 'HU-BA', 'admin_level': '6', 'name:en': 'Baranya'},
    {'ISO3166-2': 'HU-ZA', 'admin_level': '6', 'name:en': 'Zala'},
    {'ISO3166-2': 'HU-TO', 'admin_level': '6', 'name:en': 'Tolna'},
    {'ISO3166-2': 'HU-GS', 'admin_level': '6', 'name:en': 'Győr-Moson-Sopron'},
    {'ISO3166-2': 'HU-VA', 'admin_level': '6', 'name:en': 'Vas'},
    {'ISO3166-2': 'HU-KE', 'admin_level': '6', 'name:en': 'Komárom-Esztergom'},
    {'ISO3166-2': 'HU-FE', 'admin_level': '6', 'name:en': 'Fejér'},
    {'ISO3166-2': 'HU-PE', 'admin_level': '6', 'name:en': 'Pest'},
    {'ISO3166-2': 'HU-BK', 'admin_level': '6', 'name:en': 'Bács-Kiskun'},
    {'ISO3166-2': 'HU-CS', 'admin_level': '6', 'name:en': 'Csongrád-Csanád'},
    {'ISO3166-2': 'HU-BE', 'admin_level': '6', 'name:en': 'Békés'},
    {'ISO3166-2': 'HU-HB', 'admin_level': '6', 'name:en': 'Hajdú-Bihar'},
    {'ISO3166-2': 'HU-SZ', 'admin_level': '6', 'name:en': 'Szabolcs-Szatmár-Bereg'},
    {'ISO3166-2': 'HU-BZ', 'admin_level': '6', 'name:en': 'Borsod-Abaúj-Zemplén'},
    {'ISO3166-2': 'HU-HE', 'admin_level': '6', 'name:en': 'Heves'},
    {'ISO3166-2': 'HU-NO', 'admin_level': '6', 'name:en': 'Nógrád'},
    {'ISO3166-2': 'HU-VE', 'admin_level': '6', 'name:en': 'Veszprém'},
    {'ISO3166-2': 'HU-JN', 'admin_level': '6', 'name:en': 'Jász-Nagykun-Szolnok'},
    {'ISO3166-2': 'HU-BU', 'admin_level': '6', 'name:en': 'Budapest'},
    {'ISO3166-2': 'ES-HU', 'admin_level': '6', 'name:en': 'Huesca'},

]
ireland = [
    {'ISO3166-2': 'IE-WW', 'admin_level': '6', 'name:en': 'County Wicklow'},
    {'ISO3166-2': 'IE-D', 'admin_level': '6', 'name:en': 'County Dublin'},
    {'ISO3166-2': 'IE-MH', 'admin_level': '6', 'name:en': 'County Meath'},
    {'ISO3166-2': 'IE-WD', 'admin_level': '6', 'name:en': 'County Waterford'},
    {'ISO3166-2': 'IE-MN', 'admin_level': '6', 'name:en': 'County Monaghan'},
    {'ISO3166-2': 'IE-CN', 'admin_level': '6', 'name:en': 'County Cavan'},
    {'ISO3166-2': 'IE-DL', 'admin_level': '6', 'name:en': 'County Donegal'},
    {'ISO3166-2': 'IE-LM', 'admin_level': '6', 'name:en': 'County Leitrim'},
    {'ISO3166-2': 'IE-KE', 'admin_level': '6', 'name:en': 'County Kildare'},
    {'ISO3166-2': 'IE-LS', 'admin_level': '6', 'name:en': 'County Laois'},
    {'ISO3166-2': 'IE-CW', 'admin_level': '6', 'name:en': 'County Carlow'},
    {'ISO3166-2': 'IE-KK', 'admin_level': '6', 'name:en': 'County Kilkenny'},
    {'ISO3166-2': 'IE-WX', 'admin_level': '6', 'name:en': 'County Wexford'},
    {'ISO3166-2': 'IE-KY', 'admin_level': '6', 'name:en': 'County Kerry'},
    {'ISO3166-2': 'IE-CO', 'admin_level': '6', 'name:en': 'County Cork'},
    {'ISO3166-2': 'IE-TA', 'admin_level': '6', 'name:en': 'County Tipperary'},
    {'ISO3166-2': 'IE-CE', 'admin_level': '6', 'name:en': 'County Clare'},
    {'ISO3166-2': 'IE-LK', 'admin_level': '6', 'name:en': 'County Limerick'},
    {'ISO3166-2': 'IE-SO', 'admin_level': '6', 'name:en': 'County Sligo'},
    {'ISO3166-2': 'IE-OY', 'admin_level': '6', 'name:en': 'County Offaly'},
    {'ISO3166-2': 'IE-RN', 'admin_level': '6', 'name:en': 'County Roscommon'},
    {'ISO3166-2': 'IE-G', 'admin_level': '6', 'name:en': 'County Galway'},
    {'ISO3166-2': 'IE-LD', 'admin_level': '6', 'name:en': 'County Longford'},
    {'ISO3166-2': 'IE-WH', 'admin_level': '6', 'name:en': 'County Westmeath'},
    {'ISO3166-2': 'IE-MO', 'admin_level': '6', 'name:en': 'County Mayo'},
    {'ISO3166-2': 'IE-LH', 'admin_level': '6', 'name:en': 'County Louth'},

]
iraq = [
    {'ISO3166-2': 'IQ-DA', 'admin_level': '4', 'name:en': 'Duhok Governorate'},
    {'ISO3166-2': 'IQ-AR', 'admin_level': '4', 'name:en': 'Erbil Governorate'},
    {'ISO3166-2': 'IQ-NI', 'admin_level': '4', 'name:en': 'Nineveh Governorate'},

]
iceland = [
    {'ISO3166-2': 'IS-1', 'admin_level': '5', 'name:en': 'Capital Region'},
    {'ISO3166-2': 'IS-7', 'admin_level': '5', 'name:en': 'Eastern Region'},
    {'ISO3166-2': 'IS-6', 'admin_level': '5', 'name:en': 'Northeastern Region'},
    {'ISO3166-2': 'IS-5', 'admin_level': '5', 'name:en': 'Northwestern Region'},
    {'ISO3166-2': 'IS-4', 'admin_level': '5', 'name:en': 'Westfjords Region'},
    {'ISO3166-2': 'IS-3', 'admin_level': '5', 'name:en': 'Western Region'},
    {'ISO3166-2': 'IS-2', 'admin_level': '5', 'name:en': 'Southern Peninsula'},
    {'ISO3166-2': 'IS-8', 'admin_level': '5', 'name:en': 'Southern Region'},

]
italy = [
    {'ISO3166-2': 'IT-82', 'admin_level': '4', 'name:en': 'Sicily'},
    {'ISO3166-2': 'IT-75', 'admin_level': '4', 'name:en': 'Apulia'},
    {'ISO3166-2': 'IT-77', 'admin_level': '4', 'name:en': 'Basilicata'},
    {'ISO3166-2': 'IT-72', 'admin_level': '4', 'name:en': 'Campania'},
    {'ISO3166-2': 'IT-62', 'admin_level': '4', 'name:en': 'Lazio'},
    {'ISO3166-2': 'IT-67', 'admin_level': '4', 'name:en': 'Molise'},
    {'ISO3166-2': 'IT-52', 'admin_level': '4', 'name:en': 'Tuscany'},
    {'ISO3166-2': 'IT-55', 'admin_level': '4', 'name:en': 'Umbria'},
    {'ISO3166-2': 'IT-45', 'admin_level': '4', 'name:en': 'Emilia-Romagna'},
    {'ISO3166-2': 'IT-34', 'admin_level': '4', 'name:en': 'Veneto'},
    {'ISO3166-2': 'IT-21', 'admin_level': '4', 'name:en': 'Piedmont'},
    {'ISO3166-2': 'IT-25', 'admin_level': '4', 'name:en': 'Lombardy'},
    {'ISO3166-2': 'IT-23', 'admin_level': '4', 'name:en': 'Aosta Valley'},
    {'ISO3166-2': 'IT-32', 'admin_level': '4', 'name:en': 'Trentino – Alto Adige/Südtirol'},
    {'ISO3166-2': 'IT-57', 'admin_level': '4', 'name:en': 'Marche'},
    {'ISO3166-2': 'IT-65', 'admin_level': '4', 'name:en': 'Abruzzo'},
    {'ISO3166-2': 'IT-36', 'admin_level': '4', 'name:en': 'Friuli – Venezia Giulia'},
    {'ISO3166-2': 'IT-42', 'admin_level': '4', 'name:en': 'Liguria'},
    {'ISO3166-2': 'IT-78', 'admin_level': '4', 'name:en': 'Calabria'},
    {'ISO3166-2': 'IT-88', 'admin_level': '4', 'name:en': 'Sardinia'},

]
liechtenstein = [
    {'ISO3166-2': 'LT-UT', 'admin_level': '4', 'name:en': 'Utena County'},
    {'ISO3166-2': 'LT-MR', 'admin_level': '4', 'name:en': 'Marijampole County'},
    {'ISO3166-2': 'LT-VL', 'admin_level': '4', 'name:en': 'Vilnius County'},
    {'ISO3166-2': 'LT-PN', 'admin_level': '4', 'name:en': 'Panevezys County'},
    {'ISO3166-2': 'LT-KU', 'admin_level': '4', 'name:en': 'Kaunas County'},
    {'ISO3166-2': 'LT-AL', 'admin_level': '4', 'name:en': 'Alytus County'},
    {'ISO3166-2': 'LT-KL', 'admin_level': '4', 'name:en': 'Klaipeda County'},
    {'ISO3166-2': 'LT-TE', 'admin_level': '4', 'name:en': 'Telsiai County'},
    {'ISO3166-2': 'LT-SA', 'admin_level': '4', 'name:en': 'Siauliai County'},
    {'ISO3166-2': 'LT-TA', 'admin_level': '4', 'name:en': 'Taurage County'},
]
morocco = [
    {'ISO3166-2': 'MA-TET', 'admin_level': '5', 'name:en': 'Tetouan Province'},
    {'ISO3166-2': 'MA-NAD', 'admin_level': '5', 'name:en': 'Nador Province'},
    {'ISO3166-2': 'MA-FAH', 'admin_level': '5', 'name:en': 'Fahs-Anjra Province'},
    {'ISO3166-2': 'MA-MDF', 'admin_level': '5', 'name:en': "M'diq-Fnideq Prefecture"},
]
moldova = [
    {'ISO3166-2': 'MD-BA', 'admin_level': '4', 'name:en': 'Bălți Municipality'},
    {'ISO3166-2': 'MD-FA', 'admin_level': '4', 'name:en': 'Fălești District'},
    {'ISO3166-2': 'MD-UN', 'admin_level': '4', 'name:en': 'Ungheni District'},
    {'ISO3166-2': 'MD-CL', 'admin_level': '4', 'name:en': 'Calarași District'},
    {'ISO3166-2': 'MD-NI', 'admin_level': '4', 'name:en': 'Nisporeni District'},
    {'ISO3166-2': 'MD-HI', 'admin_level': '4', 'name:en': 'Hîncești District'},
    {'ISO3166-2': 'MD-TE', 'admin_level': '4', 'name:en': 'Telenești District'},
    {'ISO3166-2': 'MD-SI', 'admin_level': '4', 'name:en': 'Sîngerei District'},
    {'ISO3166-2': 'MD-ED', 'admin_level': '4', 'name:en': 'Edineț District'},
    {'ISO3166-2': 'MD-BR', 'admin_level': '4', 'name:en': 'Briceni District'},
    {'ISO3166-2': 'MD-OC', 'admin_level': '4', 'name:en': 'Ocnița District'},
    {'ISO3166-2': 'MD-DO', 'admin_level': '4', 'name:en': 'Dondușeni District'},
    {'ISO3166-2': 'MD-CS', 'admin_level': '4', 'name:en': 'Căușeni District'},
    {'ISO3166-2': 'MD-SV', 'admin_level': '4', 'name:en': 'Ștefan Vodă District'},
    {'ISO3166-2': 'MD-ST', 'admin_level': '4', 'name:en': 'Strășeni District'},
    {'ISO3166-2': 'ES-MD', 'admin_level': '4', 'name:en': 'Community of Madrid', 'border_type': 'region'},
    {'ISO3166-2': 'MD-BS', 'admin_level': '4', 'name:en': 'Basarabeasca District'},
    {'ISO3166-2': 'MD-CM', 'admin_level': '4', 'name:en': 'Cimișlia District'},
    {'ISO3166-2': 'MD-RE', 'admin_level': '4', 'name:en': 'Rezina District'},
    {'ISO3166-2': 'MD-IA', 'admin_level': '4', 'name:en': 'Ialoveni District'},
    {'ISO3166-2': 'MD-CU', 'admin_level': '4', 'name:en': 'Chișinău Municipality'},
    {'ISO3166-2': 'MD-AN', 'admin_level': '4', 'name:en': 'Anenii Noi District'},
    {'ISO3166-2': 'MD-DU', 'admin_level': '4', 'name:en': 'Dubăsari District'},
    {'ISO3166-2': 'MD-CR', 'admin_level': '4', 'name:en': 'Criuleni District'},
    {'ISO3166-2': 'MD-OR', 'admin_level': '4', 'name:en': 'Orhei District'},
    {'ISO3166-2': 'MD-SO', 'admin_level': '4', 'name:en': 'Soroca District'},
    {'ISO3166-2': 'MD-FL', 'admin_level': '4', 'name:en': 'Florești District'},
    {'ISO3166-2': 'MD-SD', 'admin_level': '4', 'name:en': 'Șoldănești District'},
    {'ISO3166-2': 'MD-GL', 'admin_level': '4', 'name:en': 'Glodeni District'},
    {'ISO3166-2': 'MD-DR', 'admin_level': '4', 'name:en': 'Drochia District'},
    {'ISO3166-2': 'MD-RI', 'admin_level': '4', 'name:en': 'Rîșcani District'},
    {'ISO3166-2': 'MD-CT', 'admin_level': '4', 'name:en': 'Cantemir District'},
    {'ISO3166-2': 'MD-LE', 'admin_level': '4', 'name:en': 'Leova District'},
    {'ISO3166-2': 'MD-GA', 'admin_level': '4', 'name:en': 'Gagauzia'},
    {'ISO3166-2': 'MD-TA', 'admin_level': '4', 'name:en': 'Taraclia District'},
    {'ISO3166-2': 'MD-CA', 'admin_level': '4', 'name:en': 'Cahul District'},
    {'ISO3166-2': 'MD-SN', 'admin_level': '4', 'name:en': 'Administrative-Territorial Units of the Left Bank of the Dniester'},
    {'ISO3166-2': 'MD-BD', 'admin_level': '4', 'name:en': 'Bender Municipality'},

]
montenegro = [
    {'ISO3166-2': 'ME-08', 'admin_level': '6', 'name:en': 'Herceg Novi Municipality'},
    {'ISO3166-2': 'ME-13', 'admin_level': '6', 'name:en': 'Plav Municipality'},
    {'ISO3166-2': 'ME-17', 'admin_level': '6', 'name:en': 'Rožaje Municipality'},
    {'ISO3166-2': 'ME-01', 'admin_level': '6', 'name:en': 'Andrijevica Municipality'},
    {'ISO3166-2': 'ME-03', 'admin_level': '6', 'name:en': 'Berane Municipality'},
    {'ISO3166-2': 'ME-16', 'admin_level': '6', 'name:en': 'Podgorica Capital City'},
    {'ISO3166-2': 'ME-02', 'admin_level': '6', 'name:en': 'Bar Municipality'},
    {'ISO3166-2': 'ME-04', 'admin_level': '6', 'name:en': 'Bijelo Polje Municipality'},
    {'ISO3166-2': 'ME-05', 'admin_level': '6', 'name:en': 'Budva Municipality'},
    {'ISO3166-2': 'ME-06', 'admin_level': '6', 'name:en': 'Old Royal Capital Cetinje'},
    {'ISO3166-2': 'ME-07', 'admin_level': '6', 'name:en': 'Danilovgrad Municipality'},
    {'ISO3166-2': 'ME-09', 'admin_level': '6', 'name:en': 'Kolašin Municipality'},
    {'ISO3166-2': 'ME-10', 'admin_level': '6', 'name:en': 'Kotor Municipality'},
    {'ISO3166-2': 'ME-11', 'admin_level': '6', 'name:en': 'Mojkovac Municipality'},
    {'ISO3166-2': 'ME-12', 'admin_level': '6', 'name:en': 'Nikšić Municipality'},
    {'ISO3166-2': 'ME-14', 'admin_level': '6', 'name:en': 'Pljevlja Municipality'},
    {'ISO3166-2': 'ME-15', 'admin_level': '6', 'name:en': 'Plužine Municipality'},
    {'ISO3166-2': 'ME-19', 'admin_level': '6', 'name:en': 'Tivat Municipality'},
    {'ISO3166-2': 'ME-20', 'admin_level': '6', 'name:en': 'Ulcinj Municipality'},
    {'ISO3166-2': 'ME-18', 'admin_level': '6', 'name:en': 'Šavnik Municipality'},
    {'ISO3166-2': 'ME-21', 'admin_level': '6', 'name:en': 'Žabljak Municipality'},
    {'ISO3166-2': 'ME-22', 'admin_level': '6', 'name:en': 'Gusinje Municipality'},
    {'ISO3166-2': 'ME-23', 'admin_level': '6', 'name:en': 'Petnjica Municipality'},
    {'ISO3166-2': 'ME-24', 'admin_level': '6', 'name:en': 'Tuzi Municipality'},
    {'ISO3166-2': 'ME-25', 'admin_level': '6', 'name:en': 'Zeta Municipality'},
]
netherlands = [
    {'ISO3166-2': 'NL-FR', 'admin_level': '4', 'name:en': 'Frisia'},
    {'ISO3166-2': 'NL-FL', 'admin_level': '4', 'name:en': 'Flevoland'},
    {'ISO3166-2': 'NL-DR', 'admin_level': '4', 'name:en': 'Drenthe'},
    {'ISO3166-2': 'NL-GE', 'admin_level': '4', 'name:en': 'Gelderland'},
    {'ISO3166-2': 'NL-OV', 'admin_level': '4', 'name:en': 'Overijssel'},
    {'ISO3166-2': 'NL-NH', 'admin_level': '4', 'name:en': 'North Holland'},
    {'ISO3166-2': 'NL-UT', 'admin_level': '4', 'name:en': 'Utrecht'},
    {'ISO3166-2': 'NL-NB', 'admin_level': '4', 'name:en': 'North Brabant'},
    {'ISO3166-2': 'NL-ZH', 'admin_level': '4', 'name:en': 'South Holland'},
    {'ISO3166-2': 'NL-LI', 'admin_level': '4', 'name:en': 'Limburg'},
    {'ISO3166-2': 'NL-ZE', 'admin_level': '4', 'name:en': 'Zeeland'},
    {'ISO3166-2': 'NL-GR', 'admin_level': '4', 'name:en': 'Groningen'},

]
norway = [
    {'ISO3166-2': 'NO-39', 'admin_level': '4', 'name:en': 'Vestfold'},
    {'ISO3166-2': 'NO-40', 'admin_level': '4', 'name:en': 'Telemark'},
    {'ISO3166-2': 'NO-11', 'admin_level': '4', 'name:en': 'Rogaland'},
    {'ISO3166-2': 'NO-31', 'admin_level': '4', 'name:en': 'Østfold'},
    {'ISO3166-2': 'NO-03', 'admin_level': '4', 'name:en': 'Oslo'},
    {'ISO3166-2': 'NO-32', 'admin_level': '4', 'name:en': 'Akershus'},
    {'ISO3166-2': 'NO-56', 'admin_level': '4', 'name:en': 'Finnmark'},
    {'ISO3166-2': 'NO-50', 'admin_level': '4', 'name:en': 'Trøndelag'},
    {'ISO3166-2': 'NO-15', 'admin_level': '4', 'name:en': 'Møre og Romsdal'},
    {'ISO3166-2': 'NO-55', 'admin_level': '4', 'name:en': 'Troms'},
    {'ISO3166-2': 'NO-18', 'admin_level': '4', 'name:en': 'Nordland'},
    {'ISO3166-2': 'NO-33', 'admin_level': '4', 'name:en': 'Buskerud'},
    {'ISO3166-2': 'NO-22', 'admin_level': '4', 'name:en': 'Jan Mayen'},
    {'ISO3166-2': 'NO-21', 'admin_level': '4', 'name:en': 'Svalbard'},
    {'ISO3166-2': 'NO-42', 'admin_level': '4', 'name:en': 'Agder'},
    {'ISO3166-2': 'NO-34', 'admin_level': '4', 'name:en': 'Innlandet'},
    {'ISO3166-2': 'NO-46', 'admin_level': '4', 'name:en': 'Vestland'},

]
poland = [
    {'ISO3166-2': 'PL-32', 'admin_level': '4', 'name:en': 'West Pomeranian Voivodeship'},
    {'ISO3166-2': 'PL-26', 'admin_level': '4', 'name:en': 'Holy Cross Voivodeship'},
    {'ISO3166-2': 'PL-06', 'admin_level': '4', 'name:en': 'Lublin Voivodeship'},
    {'ISO3166-2': 'PL-14', 'admin_level': '4', 'name:en': 'Masovian Voivodeship'},
    {'ISO3166-2': 'PL-18', 'admin_level': '4', 'name:en': 'Subcarpathian Voivodeship'},
    {'ISO3166-2': 'PL-08', 'admin_level': '4', 'name:en': 'Lubusz Voivodeship'},
    {'ISO3166-2': 'PL-30', 'admin_level': '4', 'name:en': 'Greater Poland Voivodeship'},
    {'ISO3166-2': 'PL-22', 'admin_level': '4', 'name:en': 'Pomeranian Voivodeship'},
    {'ISO3166-2': 'PL-04', 'admin_level': '4', 'name:en': 'Kuyavian-Pomeranian Voivodeship'},
    {'ISO3166-2': 'PL-28', 'admin_level': '4', 'name:en': 'Warmian-Masurian Voivodeship'},
    {'ISO3166-2': 'PL-02', 'admin_level': '4', 'name:en': 'Lower Silesian Voivodeship'},
    {'ISO3166-2': 'PL-10', 'admin_level': '4', 'name:en': 'Łódź Voivodeship'},
    {'ISO3166-2': 'PL-12', 'admin_level': '4', 'name:en': 'Lesser Poland Voivodeship'},
    {'ISO3166-2': 'PL-16', 'admin_level': '4', 'name:en': 'Opole Voivodeship'},
    {'ISO3166-2': 'PL-20', 'admin_level': '4', 'name:en': 'Podlaskie Voivodeship'},
    {'ISO3166-2': 'PL-24', 'admin_level': '4', 'name:en': 'Silesian Voivodeship'},

]
portugal = [
    {'ISO3166-2': 'PT-08', 'admin_level': '6', 'name:en': 'Faro', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-11', 'admin_level': '6', 'name:en': 'Lisbon', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-13', 'admin_level': '6', 'name:en': 'Porto', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-03', 'admin_level': '6', 'name:en': 'Braga', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-16', 'admin_level': '6', 'name:en': 'Viana do Castelo', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-09', 'admin_level': '6', 'name:en': 'Guarda', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-04', 'admin_level': '6', 'name:en': 'Bragança', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-01', 'admin_level': '6', 'name:en': 'Aveiro', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-18', 'admin_level': '6', 'name:en': 'Viseu', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-17', 'admin_level': '6', 'name:en': 'Vila Real', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-05', 'admin_level': '6', 'name:en': 'Castelo Branco', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-06', 'admin_level': '6', 'name:en': 'Coimbra', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-10', 'admin_level': '6', 'name:en': 'Leiria', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-14', 'admin_level': '6', 'name:en': 'Santarém', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-12', 'admin_level': '6', 'name:en': 'Portalegre', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-07', 'admin_level': '6', 'name:en': 'Évora', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-02', 'admin_level': '6', 'name:en': 'Beja', 'border_type': 'distrito'},
    {'ISO3166-2': 'PT-15', 'admin_level': '6', 'name:en': 'Setúbal', 'border_type': 'distrito'},
]
romania = [
    {'ISO3166-2': 'RO-BN', 'admin_level': '4', 'name:en': 'Bistrița-Năsăud'},
    {'ISO3166-2': 'RO-MM', 'admin_level': '4', 'name:en': 'Maramureș'},
    {'ISO3166-2': 'RO-SM', 'admin_level': '4', 'name:en': 'Satu Mare'},
    {'ISO3166-2': 'RU-ROS', 'admin_level': '4', 'name:en': 'Rostov Oblast', 'border_type': 'region'},
    {'ISO3166-2': 'RO-SJ', 'admin_level': '4', 'name:en': 'Sălaj'},
    {'ISO3166-2': 'RO-BH', 'admin_level': '4', 'name:en': 'Bihor'},
    {'ISO3166-2': 'RO-CJ', 'admin_level': '4', 'name:en': 'Cluj'},
    {'ISO3166-2': 'RO-AB', 'admin_level': '4', 'name:en': 'Alba'},
    {'ISO3166-2': 'RO-B', 'admin_level': '4', 'name:en': 'Bucharest'},
    {'ISO3166-2': 'RO-SV', 'admin_level': '4', 'name:en': 'Suceava'},
    {'ISO3166-2': 'RO-MS', 'admin_level': '4', 'name:en': 'Mureș'},
    {'ISO3166-2': 'RO-SB', 'admin_level': '4', 'name:en': 'Sibiu'},
    {'ISO3166-2': 'RO-BV', 'admin_level': '4', 'name:en': 'Brașov'},
    {'ISO3166-2': 'RO-CV', 'admin_level': '4', 'name:en': 'Covasna'},
    {'ISO3166-2': 'RO-HR', 'admin_level': '4', 'name:en': 'Harghita'},
    {'ISO3166-2': 'RO-NT', 'admin_level': '4', 'name:en': 'Neamț'},
    {'ISO3166-2': 'RO-BC', 'admin_level': '4', 'name:en': 'Bacău'},
    {'ISO3166-2': 'RO-AR', 'admin_level': '4', 'name:en': 'Arad'},
    {'ISO3166-2': 'RO-HD', 'admin_level': '4', 'name:en': 'Hunedoara'},
    {'ISO3166-2': 'RO-BT', 'admin_level': '4', 'name:en': 'Botoșani'},
    {'ISO3166-2': 'RO-IS', 'admin_level': '4', 'name:en': 'Iași'},
    {'ISO3166-2': 'RO-VS', 'admin_level': '4', 'name:en': 'Vaslui'},
    {'ISO3166-2': 'RO-VN', 'admin_level': '4', 'name:en': 'Vrancea'},
    {'ISO3166-2': 'RO-GL', 'admin_level': '4', 'name:en': 'Galați'},
    {'ISO3166-2': 'RO-GJ', 'admin_level': '4', 'name:en': 'Gorj'},
    {'ISO3166-2': 'RO-VL', 'admin_level': '4', 'name:en': 'Vâlcea'},
    {'ISO3166-2': 'RO-AG', 'admin_level': '4', 'name:en': 'Argeș'},
    {'ISO3166-2': 'RO-DB', 'admin_level': '4', 'name:en': 'Dâmbovița'},
    {'ISO3166-2': 'RO-PH', 'admin_level': '4', 'name:en': 'Prahova'},
    {'ISO3166-2': 'RO-BZ', 'admin_level': '4', 'name:en': 'Buzău'},
    {'ISO3166-2': 'RO-BR', 'admin_level': '4', 'name:en': 'Brăila'},
    {'ISO3166-2': 'RO-IL', 'admin_level': '4', 'name:en': 'Ialomița'},
    {'ISO3166-2': 'RO-TM', 'admin_level': '4', 'name:en': 'Timiș'},
    {'ISO3166-2': 'RO-CS', 'admin_level': '4', 'name:en': 'Caraș-Severin'},
    {'ISO3166-2': 'RO-MH', 'admin_level': '4', 'name:en': 'Mehedinți'},
    {'ISO3166-2': 'RO-DJ', 'admin_level': '4', 'name:en': 'Dolj'},
    {'ISO3166-2': 'RO-OT', 'admin_level': '4', 'name:en': 'Olt'},
    {'ISO3166-2': 'RO-TR', 'admin_level': '4', 'name:en': 'Teleorman'},
    {'ISO3166-2': 'RO-GR', 'admin_level': '4', 'name:en': 'Giurgiu'},
    {'ISO3166-2': 'RO-IF', 'admin_level': '4', 'name:en': 'Ilfov'},
    {'ISO3166-2': 'RO-CL', 'admin_level': '4', 'name:en': 'Călărași'},
    {'ISO3166-2': 'RO-CT', 'admin_level': '4', 'name:en': 'Constanța'},
    {'ISO3166-2': 'RO-TL', 'admin_level': '4', 'name:en': 'Tulcea'},
]
serbia = [
{'ISO3166-2': 'RS-07', 'admin_level': '6', 'name:en': 'Srem Administrative District'},
{'ISO3166-2': 'RS-04', 'admin_level': '6', 'name:en': 'South Banat Administrative District'},
{'ISO3166-2': 'RS-03', 'admin_level': '6', 'name:en': 'North Banat Administrative District'},
{'ISO3166-2': 'RS-01', 'admin_level': '6', 'name:en': 'North Backa Administrative District'},
{'ISO3166-2': 'RS-02', 'admin_level': '6', 'name:en': 'Central Banat Administrative District'},
{'ISO3166-2': 'RS-05', 'admin_level': '6', 'name:en': 'West Backa Administrative District'},
{'ISO3166-2': 'RS-06', 'admin_level': '6', 'name:en': 'South Backa Administrative District'},
{'ISO3166-2': 'RS-00', 'admin_level': '6', 'name:en': 'City of Belgrade'},
{'ISO3166-2': 'RS-14', 'admin_level': '6', 'name:en': 'Bor Administrative District'},
{'ISO3166-2': 'RS-08', 'admin_level': '6', 'name:en': 'Macva Administrative District'},
{'ISO3166-2': 'RS-24', 'admin_level': '6', 'name:en': 'Pcinja Administrative District'},
{'ISO3166-2': 'RS-09', 'admin_level': '6', 'name:en': 'Kolubara Administrative District'},
{'ISO3166-2': 'RS-10', 'admin_level': '6', 'name:en': 'Podunavlje Administrative District'},
{'ISO3166-2': 'RS-11', 'admin_level': '6', 'name:en': 'Branicevo Administrative District'},
{'ISO3166-2': 'RS-12', 'admin_level': '6', 'name:en': 'Sumadija Administrative District'},
{'ISO3166-2': 'RS-13', 'admin_level': '6', 'name:en': 'Pomoravlje Administrative District'},
{'ISO3166-2': 'RS-17', 'admin_level': '6', 'name:en': 'Moravica Administrative District'},
{'ISO3166-2': 'RS-15', 'admin_level': '6', 'name:en': 'Zajecar Administrative District'},
{'ISO3166-2': 'RS-16', 'admin_level': '6', 'name:en': 'Zlatibor Administrative District'},
{'ISO3166-2': 'RS-18', 'admin_level': '6', 'name:en': 'Raska Administrative District'},
{'ISO3166-2': 'RS-22', 'admin_level': '6', 'name:en': 'Pirot Administrative District'},
{'ISO3166-2': 'RS-23', 'admin_level': '6', 'name:en': 'Jablanica Administrative District'},
{'ISO3166-2': 'RS-21', 'admin_level': '6', 'name:en': 'Toplica Administrative District'},
{'ISO3166-2': 'RS-20', 'admin_level': '6', 'name:en': 'Nisava Administrative District'},
{'ISO3166-2': 'RS-19', 'admin_level': '6', 'name:en': 'Rasina Administrative District'},
]
russia = [
{'ISO3166-2': 'RU-MOS', 'admin_level': '4', 'name:en': 'Moscow Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-RYA', 'admin_level': '4', 'name:en': 'Ryazan Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-LIP', 'admin_level': '4', 'name:en': 'Lipetsk Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-TAM', 'admin_level': '4', 'name:en': 'Tambov Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-VOR', 'admin_level': '4', 'name:en': 'Voronezh Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-PNZ', 'admin_level': '4', 'name:en': 'Penza Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-SAR', 'admin_level': '4', 'name:en': 'Saratov Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-NIZ', 'admin_level': '4', 'name:en': 'Nizhny Novgorod Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-MO', 'admin_level': '4', 'name:en': 'Republic of Mordovia', 'border_type': 'region'},
{'ISO3166-2': 'RU-VLA', 'admin_level': '4', 'name:en': 'Vladimir Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-KRS', 'admin_level': '4', 'name:en': 'Kursk Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-ORL', 'admin_level': '4', 'name:en': 'Oryol Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-VGG', 'admin_level': '4', 'name:en': 'Volgograd Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-TUL', 'admin_level': '4', 'name:en': 'Tula Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-YAR', 'admin_level': '4', 'name:en': 'Yaroslavl Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-KLU', 'admin_level': '4', 'name:en': 'Kaluga Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-SMO', 'admin_level': '4', 'name:en': 'Smolensk Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-BRY', 'admin_level': '4', 'name:en': 'Bryansk Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-BEL', 'admin_level': '4', 'name:en': 'Belgorod Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-ROS', 'admin_level': '4', 'name:en': 'Rostov Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-IVA', 'admin_level': '4', 'name:en': 'Ivanovo Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-KOS', 'admin_level': '4', 'name:en': 'Kostroma Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-NGR', 'admin_level': '4', 'name:en': 'Novgorod Oblast'},
{'ISO3166-2': 'RU-MOW', 'admin_level': '4', 'name:en': 'Moscow'},
{'ISO3166-2': 'RU-KGD', 'admin_level': '4', 'name:en': 'Kaliningrad', 'border_type': 'region'},
{'ISO3166-2': 'RU-STA', 'admin_level': '4', 'name:en': 'Stavropol Krai', 'border_type': 'region'},
{'ISO3166-2': 'RU-KDA', 'admin_level': '4', 'name:en': 'Krasnodar Krai', 'border_type': 'region'},
{'ISO3166-2': 'RU-KL', 'admin_level': '4', 'name:en': 'Republic of Kalmykia', 'border_type': 'region'},
{'ISO3166-2': 'RU-DA', 'admin_level': '4', 'name:en': 'Dagestan', 'border_type': 'region'},
{'ISO3166-2': 'RU-CE', 'admin_level': '4', 'name:en': 'Chechnya'},
{'ISO3166-2': 'RU-KC', 'admin_level': '4', 'name:en': 'Karachay-Cherkessia'},
{'ISO3166-2': 'RU-KB', 'admin_level': '4', 'name:en': 'Kabardino-Balkaria'},
{'ISO3166-2': 'RU-SE', 'admin_level': '4', 'name:en': 'Republic of North Ossetia – Alania'},
{'ISO3166-2': 'RU-AST', 'admin_level': '4', 'name:en': 'Astrakhan Oblast', 'border_type': 'region'},
{'ISO3166-2': 'RU-VLG', 'admin_level': '4', 'name:en': 'Vologda Oblast'},
{'ISO3166-2': 'RU-ARK', 'admin_level': '4', 'name:en': 'Arkhangelsk Oblast'},
{'ISO3166-2': 'RU-PSK', 'admin_level': '4', 'name:en': 'Pskov Oblast'},
{'ISO3166-2': 'RU-LEN', 'admin_level': '4', 'name:en': 'Leningrad Oblast'},
{'ISO3166-2': 'RU-IN', 'admin_level': '4', 'name:en': 'Ingushetia'},
{'ISO3166-2': 'RU-AD', 'admin_level': '4', 'name:en': 'Republic of Adygea', 'border_type': 'region'},
{'ISO3166-2': 'RU-NEN', 'admin_level': '4', 'name:en': 'Nenets Autonomous Okrug'},
{'ISO3166-2': 'RU-SPE', 'admin_level': '4', 'name:en': 'Saint Petersburg'},
{'ISO3166-2': 'RU-KR', 'admin_level': '4', 'name:en': 'Republic of Karelia'},
{'ISO3166-2': 'RU-TVE', 'admin_level': '4', 'name:en': 'Tver Oblast'},
{'ISO3166-2': 'RU-MUR', 'admin_level': '4', 'name:en': 'Murmansk Oblast'},

]
sweden = [
{'ISO3166-2': 'SE-BD', 'admin_level': '4', 'name:en': 'Norrbotten County'},
{'ISO3166-2': 'SE-AC', 'admin_level': '4', 'name:en': 'Västerbotten County'},
{'ISO3166-2': 'SE-Z', 'admin_level': '4', 'name:en': 'Jämtland County'},
{'ISO3166-2': 'SE-Y', 'admin_level': '4', 'name:en': 'Västernorrland County'},
{'ISO3166-2': 'SE-X', 'admin_level': '4', 'name:en': 'Gävleborg County'},
{'ISO3166-2': 'SE-W', 'admin_level': '4', 'name:en': 'Dalarna County'},
{'ISO3166-2': 'SE-C', 'admin_level': '4', 'name:en': 'Uppsala County'},
{'ISO3166-2': 'SE-U', 'admin_level': '4', 'name:en': 'Västmanland County'},
{'ISO3166-2': 'SE-T', 'admin_level': '4', 'name:en': 'Örebro County'},
{'ISO3166-2': 'SE-S', 'admin_level': '4', 'name:en': 'Värmland County'},
{'ISO3166-2': 'SE-O', 'admin_level': '4', 'name:en': 'Västra Götaland County'},
{'ISO3166-2': 'SE-F', 'admin_level': '4', 'name:en': 'Jönköping County'},
{'ISO3166-2': 'SE-D', 'admin_level': '4', 'name:en': 'Södermanland County'},
{'ISO3166-2': 'SE-AB', 'admin_level': '4', 'name:en': 'Stockholm County'},
{'ISO3166-2': 'SE-N', 'admin_level': '4', 'name:en': 'Halland County'},
{'ISO3166-2': 'SE-M', 'admin_level': '4', 'name:en': 'Skåne County'},
{'ISO3166-2': 'SE-G', 'admin_level': '4', 'name:en': 'Kronoberg County'},
{'ISO3166-2': 'SE-K', 'admin_level': '4', 'name:en': 'Blekinge County'},
{'ISO3166-2': 'SE-H', 'admin_level': '4', 'name:en': 'Kalmar County'},
{'ISO3166-2': 'SE-E', 'admin_level': '4', 'name:en': 'Östergötland County'},
{'ISO3166-2': 'SE-I', 'admin_level': '4', 'name:en': 'Gotland County'},

]
slovakia = [
{'ISO3166-2': 'SK-BL', 'admin_level': '4', 'name:en': 'Region of Bratislava'},
{'ISO3166-2': 'SK-TA', 'admin_level': '4', 'name:en': 'Region of Trnava'},
{'ISO3166-2': 'SK-TC', 'admin_level': '4', 'name:en': 'Region of Trenčín'},
{'ISO3166-2': 'SK-NI', 'admin_level': '4', 'name:en': 'Region of Nitra'},
{'ISO3166-2': 'SK-ZI', 'admin_level': '4', 'name:en': 'Region of Žilina'},
{'ISO3166-2': 'SK-BC', 'admin_level': '4', 'name:en': 'Region of Banská Bystrica'},
{'ISO3166-2': 'SK-PV', 'admin_level': '4', 'name:en': 'Region of Prešov'},
{'ISO3166-2': 'SK-KI', 'admin_level': '4', 'name:en': 'Region of Košice'},
]
syria = [
{'ISO3166-2': 'SY-HA', 'admin_level': '4', 'name:en': 'Al-Hasaka Governorate'},
{'ISO3166-2': 'SY-RA', 'admin_level': '4', 'name:en': 'Ar-Raqqa Governorate'},
{'ISO3166-2': 'SY-HL', 'admin_level': '4', 'name:en': 'Aleppo Governorate'},
{'ISO3166-2': 'SY-ID', 'admin_level': '4', 'name:en': 'Idleb Governorate'},
{'ISO3166-2': 'SY-LA', 'admin_level': '4', 'name:en': 'Lattakia Governorate'},
]
turkey = [
{'ISO3166-2': 'TR-50', 'admin_level': '4', 'name:en': 'Nevşehir'},
{'ISO3166-2': 'TR-66', 'admin_level': '4', 'name:en': 'Yozgat'},
{'ISO3166-2': 'TR-38', 'admin_level': '4', 'name:en': 'Kayseri'},
{'ISO3166-2': 'TR-40', 'admin_level': '4', 'name:en': 'Kırşehir'},
{'ISO3166-2': 'TR-68', 'admin_level': '4', 'name:en': 'Aksaray'},
{'ISO3166-2': 'TR-51', 'admin_level': '4', 'name:en': 'Niğde'},
{'ISO3166-2': 'TR-01', 'admin_level': '4', 'name:en': 'Adana'},
{'ISO3166-2': 'TR-80', 'admin_level': '4', 'name:en': 'Osmaniye'},
{'ISO3166-2': 'TR-30', 'admin_level': '4', 'name:en': 'Hakkâri'},
{'ISO3166-2': 'TR-36', 'admin_level': '4', 'name:en': 'Kars'},
{'ISO3166-2': 'TR-25', 'admin_level': '4', 'name:en': 'Erzurum'},
{'ISO3166-2': 'TR-04', 'admin_level': '4', 'name:en': 'Ağrı'},
{'ISO3166-2': 'TR-76', 'admin_level': '4', 'name:en': 'Iğdır'},
{'ISO3166-2': 'TR-31', 'admin_level': '4', 'name:en': 'Hatay'},
{'ISO3166-2': 'TR-33', 'admin_level': '4', 'name:en': 'Mersin'},
{'ISO3166-2': 'TR-07', 'admin_level': '4', 'name:en': 'Antalya'},
{'ISO3166-2': 'TR-42', 'admin_level': '4', 'name:en': 'Konya'},
{'ISO3166-2': 'TR-32', 'admin_level': '4', 'name:en': 'Isparta'},
{'ISO3166-2': 'TR-48', 'admin_level': '4', 'name:en': 'Muğla'},
{'ISO3166-2': 'TR-70', 'admin_level': '4', 'name:en': 'Karaman'},
{'ISO3166-2': 'TR-46', 'admin_level': '4', 'name:en': 'Kahramanmaraş'},
{'ISO3166-2': 'TR-27', 'admin_level': '4', 'name:en': 'Gaziantep'},
{'ISO3166-2': 'TR-79', 'admin_level': '4', 'name:en': 'Kilis'},
{'ISO3166-2': 'TR-02', 'admin_level': '4', 'name:en': 'Adıyaman'},
{'ISO3166-2': 'TR-09', 'admin_level': '4', 'name:en': 'Aydın'},
{'ISO3166-2': 'TR-35', 'admin_level': '4', 'name:en': 'Izmir'},
{'ISO3166-2': 'TR-45', 'admin_level': '4', 'name:en': 'Manisa'},
{'ISO3166-2': 'TR-20', 'admin_level': '4', 'name:en': 'Denizli'},
{'ISO3166-2': 'TR-64', 'admin_level': '4', 'name:en': 'Uşak'},
{'ISO3166-2': 'TR-03', 'admin_level': '4', 'name:en': 'Afyonkarahisar'},
{'ISO3166-2': 'TR-43', 'admin_level': '4', 'name:en': 'Kütahya'},
{'ISO3166-2': 'TR-11', 'admin_level': '4', 'name:en': 'Bilecik'},
{'ISO3166-2': 'TR-26', 'admin_level': '4', 'name:en': 'Eskişehir'},
{'ISO3166-2': 'TR-06', 'admin_level': '4', 'name:en': 'Ankara'},
{'ISO3166-2': 'TR-71', 'admin_level': '4', 'name:en': 'Kırıkkale'},
{'ISO3166-2': 'TR-60', 'admin_level': '4', 'name:en': 'Tokat'},
{'ISO3166-2': 'TR-58', 'admin_level': '4', 'name:en': 'Sivas'},
{'ISO3166-2': 'TR-44', 'admin_level': '4', 'name:en': 'Malatya'},
{'ISO3166-2': 'TR-63', 'admin_level': '4', 'name:en': 'Şanlıurfa'},
{'ISO3166-2': 'TR-21', 'admin_level': '4', 'name:en': 'Diyarbakır'},
{'ISO3166-2': 'TR-47', 'admin_level': '4', 'name:en': 'Mardin'},
{'ISO3166-2': 'TR-72', 'admin_level': '4', 'name:en': 'Batman'},
{'ISO3166-2': 'TR-73', 'admin_level': '4', 'name:en': 'Şırnak'},
{'ISO3166-2': 'TR-49', 'admin_level': '4', 'name:en': 'Muş'},
{'ISO3166-2': 'TR-13', 'admin_level': '4', 'name:en': 'Bitlis'},
{'ISO3166-2': 'TR-65', 'admin_level': '4', 'name:en': 'Van'},
{'ISO3166-2': 'TR-23', 'admin_level': '4', 'name:en': 'Elazığ'},
{'ISO3166-2': 'TR-12', 'admin_level': '4', 'name:en': 'Bingöl'},
{'ISO3166-2': 'TR-24', 'admin_level': '4', 'name:en': 'Erzincan'},
{'ISO3166-2': 'TR-69', 'admin_level': '4', 'name:en': 'Bayburt'},
{'ISO3166-2': 'TR-61', 'admin_level': '4', 'name:en': 'Trabzon'},
{'ISO3166-2': 'TR-08', 'admin_level': '4', 'name:en': 'Artvin'},
{'ISO3166-2': 'TR-28', 'admin_level': '4', 'name:en': 'Giresun'},
{'ISO3166-2': 'TR-52', 'admin_level': '4', 'name:en': 'Ordu'},
{'ISO3166-2': 'TR-55', 'admin_level': '4', 'name:en': 'Samsun'},
{'ISO3166-2': 'TR-05', 'admin_level': '4', 'name:en': 'Amasya'},
{'ISO3166-2': 'TR-19', 'admin_level': '4', 'name:en': 'Çorum'},
{'ISO3166-2': 'TR-18', 'admin_level': '4', 'name:en': 'Çankırı'},
{'ISO3166-2': 'TR-78', 'admin_level': '4', 'name:en': 'Karabük'},
{'ISO3166-2': 'TR-37', 'admin_level': '4', 'name:en': 'Kastamonu'},
{'ISO3166-2': 'TR-57', 'admin_level': '4', 'name:en': 'Sinop'},
{'ISO3166-2': 'TR-74', 'admin_level': '4', 'name:en': 'Bartın'},
{'ISO3166-2': 'TR-67', 'admin_level': '4', 'name:en': 'Zonguldak'},
{'ISO3166-2': 'TR-81', 'admin_level': '4', 'name:en': 'Düzce'},
{'ISO3166-2': 'TR-14', 'admin_level': '4', 'name:en': 'Bolu'},
{'ISO3166-2': 'TR-54', 'admin_level': '4', 'name:en': 'Sakarya'},
{'ISO3166-2': 'TR-16', 'admin_level': '4', 'name:en': 'Bursa'},
{'ISO3166-2': 'TR-10', 'admin_level': '4', 'name:en': 'Balıkesir'},
{'ISO3166-2': 'TR-22', 'admin_level': '4', 'name:en': 'Edirne'},
{'ISO3166-2': 'TR-39', 'admin_level': '4', 'name:en': 'Kırklareli'},
{'ISO3166-2': 'TR-59', 'admin_level': '4', 'name:en': 'Tekirdağ'},
{'ISO3166-2': 'TR-17', 'admin_level': '4', 'name:en': 'Canakkale'},
{'ISO3166-2': 'TR-77', 'admin_level': '4', 'name:en': 'Yalova'},
{'ISO3166-2': 'TR-41', 'admin_level': '4', 'name:en': 'Kocaeli'},
{'ISO3166-2': 'TR-34', 'admin_level': '4', 'name:en': 'Istanbul'},
{'ISO3166-2': 'TR-62', 'admin_level': '4', 'name:en': 'Tunceli', 'border_type': 'province'},
{'ISO3166-2': 'TR-29', 'admin_level': '4', 'name:en': 'Gümüşhane'},
{'ISO3166-2': 'TR-53', 'admin_level': '4', 'name:en': 'Rize'},
{'ISO3166-2': 'TR-56', 'admin_level': '4', 'name:en': 'Siirt'},
{'ISO3166-2': 'TR-75', 'admin_level': '4', 'name:en': 'Ardahan'},
{'ISO3166-2': 'TR-15', 'admin_level': '4', 'name:en': 'Burdur'},
]
ukraine = [
{'ISO3166-2': 'UA-65', 'admin_level': '4', 'name:en': 'Kherson Oblast'},
{'ISO3166-2': 'UA-07', 'admin_level': '4', 'name:en': 'Volyn Oblast'},
{'ISO3166-2': 'UA-56', 'admin_level': '4', 'name:en': 'Rivne Oblast'},
{'ISO3166-2': 'UA-18', 'admin_level': '4', 'name:en': 'Zhytomyr Oblast'},
{'ISO3166-2': 'UA-32', 'admin_level': '4', 'name:en': 'Kyiv Oblast'},
{'ISO3166-2': 'UA-74', 'admin_level': '4', 'name:en': 'Chernihiv Oblast'},
{'ISO3166-2': 'UA-59', 'admin_level': '4', 'name:en': 'Sumy Oblast'},
{'ISO3166-2': 'UA-63', 'admin_level': '4', 'name:en': 'Kharkiv Oblast'},
{'ISO3166-2': 'UA-09', 'admin_level': '4', 'name:en': 'Luhansk Oblast'},
{'ISO3166-2': 'UA-14', 'admin_level': '4', 'name:en': 'Donetsk Oblast'},
{'ISO3166-2': 'UA-23', 'admin_level': '4', 'name:en': 'Zaporizhia Oblast'},
{'ISO3166-2': 'UA-46', 'admin_level': '4', 'name:en': 'Lviv Oblast'},
{'ISO3166-2': 'UA-26', 'admin_level': '4', 'name:en': 'Ivano-Frankivsk Oblast'},
{'ISO3166-2': 'UA-21', 'admin_level': '4', 'name:en': 'Zakarpattia Oblast'},
{'ISO3166-2': 'UA-61', 'admin_level': '4', 'name:en': 'Ternopil Oblast'},
{'ISO3166-2': 'UA-77', 'admin_level': '4', 'name:en': 'Chernivtsi Oblast'},
{'ISO3166-2': 'UA-51', 'admin_level': '4', 'name:en': 'Odesa Oblast'},
{'ISO3166-2': 'UA-48', 'admin_level': '4', 'name:en': 'Mykolaiv Oblast'},
{'ISO3166-2': 'UA-43', 'admin_level': '4', 'name:en': 'Autonomous Republic of Crimea'},
{'ISO3166-2': 'UA-05', 'admin_level': '4', 'name:en': 'Vinnytsia Oblast'},
{'ISO3166-2': 'UA-68', 'admin_level': '4', 'name:en': 'Khmelnytskyi Oblast'},
{'ISO3166-2': 'UA-71', 'admin_level': '4', 'name:en': 'Cherkasy Oblast'},
{'ISO3166-2': 'UA-53', 'admin_level': '4', 'name:en': 'Poltava Oblast'},
{'ISO3166-2': 'UA-12', 'admin_level': '4', 'name:en': 'Dnipropetrovsk Oblast'},
{'ISO3166-2': 'UA-35', 'admin_level': '4', 'name:en': 'Kirovohrad Oblast'},
{'ISO3166-2': 'UA-30', 'admin_level': '4', 'name:en': 'Kyiv'},
{'ISO3166-2': 'UA-40', 'admin_level': '4', 'name:en': 'Sevastopol'},
]

